### PR TITLE
Fix empty request streaming hanging forever

### LINKED ISSUE #2590: HTTP Request filtering hangs until timeout since 3.107.0
macOS
HTTP2
Node
Started in https://github.com/metalbear-co/mirrord/tree/3.107.0
Probably related to the streaming feature

### PR DESCRIPTION
**Pull request by aviramha**
Closes #2590

### CODE REVIEW

File: mirrord/agent/src/steal/connection.rs [hunk 1]
```diff
@@ -190,9 +192,25 @@ impl Client {
...
+                                    request_id,
+                                },
+                            ));
+                            if let Err(e) = tx.send(message).await {
+                                warn!(?e, ?connection_id, ?request_id, ?request.port, "failed to send chunked request empty body");
+                                return;
+                            }
+                        }
                     }
                 }
```
Comment (Razz4780) [inline mirrord/agent/src/steal/connection.rs:215]: I think you can just remove this entirely and don't use `is_last` from first `next_frames()` call at all. Same thing will happen in the first iteration of the loop below

File: mirrord/agent/src/steal/connection.rs [hunk 2]
```diff
@@ -169,6 +170,7 @@ impl Client {
                     },
                     mut body,
                 ) = request.request.into_parts();
+                tracing::trace!(?connection_id, "starting request");
```
Comment (Razz4780) [inline mirrord/agent/src/steal/connection.rs:173]: Maybe move this to the top of this `tokio::task`? And also log `framed` and `chunked` variables

**Review by Razz4780 — CHANGES_REQUESTED** [review]

File: mirrord/agent/src/steal/connection.rs (hunk 1 above)
Comment (aviramha) [reply mirrord/agent/src/steal/connection.rs:215]: Smart

**Review by Razz4780 — APPROVED** [review]
