### PR TITLE
Add integration test, fix wrong warning

### LINKED ISSUE #2812: Add test for double bind on port 0
follow up on [https://github.com/metalbear-co/mirrord/pull/2811](https://github.com/metalbear-co/mirrord/pull/2811)

also found this false warning:

```
2024-10-09T13:52:17.702198Z  WARN ThreadId(03) bind: mirrord_layer::socket::ops: Port 0 was not included in the filtered ports, and also not in the non-filtered ports, and will therefore be bound locally. If this is intentional, ignore this warning. If you want the http filter to apply to this port, add it to `feature.network.incoming.http_filter.ports`. If you want to steal all the traffic of this port, add it to `feature.network.incoming.ports`. sockfd=59 address_length=28 pid=4038
```

### PR DESCRIPTION
**Pull request by t4lz**
Closes #2812

### CODE REVIEW

File: mirrord/layer/src/socket/ops.rs [hunk 1]
```diff
@@ -258,8 +258,8 @@ pub(super) fn bind(
     }
 
     // To handle #1458, we don't ignore port `0` for UDP.
-    if (is_ignored_tcp_port(&requested_address, incoming_config)
```
Comment (aviramha) [inline mirrord/layer/src/socket/ops.rs:261]: why?

Comment (aviramha) [reply mirrord/layer/src/socket/ops.rs:261]: oh I realize now, but that's not a solution -this warning can also happen with tcp.. (just more rare)

Comment (aviramha) [reply mirrord/layer/src/socket/ops.rs:261]: I think it should still fail if it was ignored, since we try to match local to remote ports when it comes to binding..

Comment (t4lz) [reply mirrord/layer/src/socket/ops.rs:261]: > I think it should still fail if it was ignored, since we try to match local to remote ports when it comes to binding..

I don't understand @aviramha

Comment (aviramha) [reply mirrord/layer/src/socket/ops.rs:261]: Perhaps clarify your original intent since I think we might not be talking about the same thing

Comment (t4lz) [reply mirrord/layer/src/socket/ops.rs:261]: Nevermind. Is [this](https://github.com/metalbear-co/mirrord/pull/2813/commits/a8e3dee2d12d3b7d2af466f821e54190d0e8a2fa) a solution? - moved the warning to `listen` so that we don't show it if the user app binds a port that is ignored for incoming but then uses it for outgoing.

Comment (aviramha) [reply mirrord/layer/src/socket/ops.rs:261]: I'm okay with this, would get another review tho.

**Review by Razz4780 — APPROVED** [review]
:+1:
