### PR TITLE
Fix layer test on macOS aarch64e

### LINKED ISSUE #3267: Investigate layer integration test failures on macOS
On macOS (aarch64e), layer integration tests fail when using the universal binary `libmirrord_layer.dylib`. To reproduce, run the command below:
```sh
./scripts/build_fat_mac.sh

MIRRORD_TEST_USE_EXISTING_LIB=../../target/universal-apple-darwin/debug/libmirrord_layer.dylib cargo test -p mirrord-layer --test spawn
```

However, when pointing `MIRRORD_TEST_USE_EXISTING_LIB` to the X86_64-apple-darwin target, the test passes.

```sh
cargo build -p mirrord-layer --target=x86_64-apple-darwin
cargo build -p mirrord-layer
MIRRORD_TEST_USE_EXISTING_LIB=../../target/X86_64-apple-darwin/debug/libmirrord_layer.dylib cargo test -p mirrord-layer --test spawn
```

### PR DESCRIPTION
**Pull request by 0x00A5**
Fix #3267

### CODE REVIEW

File: mirrord/layer/tests/common/mod.rs [hunk 1]
```diff
@@ -1383,20 +1383,44 @@ pub fn get_env(
...
+            "MIRRORD_MACOS_ARM64_LIBRARY".to_string(),
+            arm64_dylib_path().to_str().unwrap().to_string(),
         ),
     ]
     .into_iter()
     .chain(extra_vars_owned)
     .collect()
 }
+
+#[cfg(all(target_os = "macos", target_arch = "aarch64"))]
```
Comment (t4lz) [inline mirrord/layer/tests/common/mod.rs:1411]: why not make it a `once` fixture like the existing `dylib_path`?
```suggestion
#[cfg(all(target_os = "macos", target_arch = "aarch64"))]
#[fixture]
#[once]
```

File: CONTRIBUTING.md [hunk 2]
```diff
@@ -201,6 +201,13 @@ And then in order to use that dylib in the tests, run the tests like this:
 MIRRORD_TEST_USE_EXISTING_LIB=../../target/universal-apple-darwin/debug/libmirrord_layer.dylib cargo test -p mirrord-layer
 ```
 
+On Apple Silicon, set `MIRRORD_MACOS_ARM64_LIBRARY` additionally to use the arm64 layer lib as well:
+```bash
+MIRRORD_TEST_USE_EXISTING_LIB=../../target/universal-apple-darwin/debug/libmirrord_layer.dylib \
+MIRRORD_MACOS_ARM64_LIBRARY=../../target/aarch64-apple-darwin/debug/libmirrord_layer.dylib \
+cargo test -p mirrord-layer
+```
```
Comment (t4lz) [inline CONTRIBUTING.md:209]: What do you think about deriving one var from the other if only one of them was specified?

File: mirrord/layer/tests/common/mod.rs [hunk 3]
```diff
@@ -1383,20 +1383,44 @@ pub fn get_env(
...
             "LD_PRELOAD".to_string(),
             dylib_path.to_str().unwrap().to_string(),
         ),
+        #[cfg(all(target_os = "macos", target_arch = "aarch64"))]
         (
-            LayerConfig::RESOLVED_CONFIG_ENV.to_string(),
-            config.encode().unwrap(),
+            "MIRRORD_MACOS_ARM64_LIBRARY".to_string(),
+            arm64_dylib_path().to_str().unwrap().to_string(),
         ),
```
Comment (t4lz) [inline mirrord/layer/tests/common/mod.rs:1404]: I think we should document somewhere why we need this to run the tests (especially as it is not needed for CI until we get arm64 darwin runners, so could be easily removed by mistake). I think here could be a place to document it. The contributing guide might also make sense, up to you which one to choose.

File: CONTRIBUTING.md (hunk 2 above)
Comment (0x00A5) [reply CONTRIBUTING.md:209]: That would be a fairly reliable fallback, giving the `universal-apple-darwin` directory exists, the build fat mac script has most likely been run at this point. We can try deriving it and use it if the path exists, otherwise build the aarch64 target.

File: mirrord/layer/tests/common/mod.rs (hunk 1 above)
Comment (0x00A5) [reply mirrord/layer/tests/common/mod.rs:1411]: I considered making it a fixture but didn't do so because it will require adding an new parameter for each tests (behind the same compilation condition here `macos` + `aarch64`). But if it's a cleaner option, I don't mind making it a fixture, since it is very similar to the `dylib_path` fixture.

File: mirrord/layer/tests/common/mod.rs (hunk 3 above)
Comment (0x00A5) [reply mirrord/layer/tests/common/mod.rs:1404]: Cool, I will add some note here

File: CONTRIBUTING.md (hunk 2 above)
Comment (0x00A5) [reply CONTRIBUTING.md]: Added deriving arm64 lib path from universal lib path as a fallback

File: mirrord/layer/tests/common/mod.rs (hunk 1 above)
Comment (t4lz) [reply mirrord/layer/tests/common/mod.rs:1427]: Ok, it's not that important. A `OnceLock` is fine, it also wouldn't be the end of the world if we didn't have a "once" mechanism, I mostly just wanted it to be consistent with the other dylib path we have.

File: changelog.d/3267.fixed.md
Comment (t4lz) [inline changelog.d/3267.fixed.md:1]: should be `internal`, not `fixed`. Everything users shouldn't care about (like how we run our tests) should be under internal.

**Review by t4lz — APPROVED** [review]
Please do mention in the contribution guide the option to directly specify the arm64 lib.
It was nice to have it documented there.

Just need to change the changelog entry file name and document in the contribution guide, so approving already.

File: changelog.d/3267.fixed.md
Comment (0x00A5) [reply changelog.d/3267.fixed.md:1]: Renamed, thanks!
