### PR TITLE
handle cases in agent where 2+ containerd sockets exist

### LINKED ISSUE #1133: Issue when multiple containerd sockets exists
### Bug Description

Source: https://discord.com/channels/933706914808889356/1080038847812997180
tl;dr - user node has 2 containerd sockets, and mirrord agent connects to the first one it finds, in the user's case that was the wrong containerd socket.

### Steps to Reproduce

install k3s and containerd separately

### Backtrace

_No response_

### Relevant Logs

_No response_

### Your operating system and version

n/a

### Local process

n/a

### Local process version

_No response_

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by aviramha**
Fixes #1133

### CODE REVIEW

File: mirrord/agent/src/runtime.rs [hunk 1]
```diff
@@ -131,23 +131,51 @@ pub(crate) struct ContainerdContainer {
...
+            Err(_) => match connect_and_find_container(
+                container_id.clone(),
+                CONTAINERD_ALTERNATIVE_SOCK_PATH,
+            )
+            .await
+            {
+                Ok(channel) => Ok(channel),
+                Err(_) => {
+                    connect_and_find_container(container_id.clone(), CONTAINERD_K3S_SOCK_PATH).await
+                }
```
Comment (DmitryDodzin) [inline mirrord/agent/src/runtime.rs:169]:
```suggestion
    async fn get_client(&self) -> Result<TasksClient<Channel>> {
        match connect_and_find_container(self.container_id.clone(), CONTAINERD_SOCK_PATH).await {
            Ok(channel) => Ok(channel),
            Err(_) => match connect_and_find_container(
                self.container_id.clone(),
                CONTAINERD_ALTERNATIVE_SOCK_PATH,
            )
            .await
            {
                Ok(channel) => Ok(channel),
                Err(_) => {
                    connect_and_find_container(self.container_id.clone(), CONTAINERD_K3S_SOCK_PATH).await
                }
```

File: mirrord/agent/src/runtime.rs [hunk 2]
```diff
@@ -131,23 +131,51 @@ pub(crate) struct ContainerdContainer {
...
-        Ok(TasksClient::new(channel))
+        }
     }
 }
 
 #[async_trait]
 impl ContainerRuntime for ContainerdContainer {
     async fn get_pid(&self) -> Result<u64> {
-        let mut client = Self::get_client().await?;
+        let mut client = Self::get_client(self.container_id.clone()).await?;
```
Comment (DmitryDodzin) [inline mirrord/agent/src/runtime.rs:178]:
```suggestion
        let mut client = self.get_client().await?;
```

File: mirrord/agent/src/runtime.rs [hunk 3]
```diff
@@ -165,7 +193,7 @@ impl ContainerRuntime for ContainerdContainer {
     }
 
     async fn pause(&self) -> Result<()> {
-        let mut client = Self::get_client().await?;
+        let mut client = Self::get_client(self.container_id.clone()).await?;
```
Comment (DmitryDodzin) [inline mirrord/agent/src/runtime.rs:196]:
```suggestion
        let mut client = self.get_client().await?;
```

File: mirrord/agent/src/runtime.rs [hunk 4]
```diff
@@ -174,7 +202,7 @@ impl ContainerRuntime for ContainerdContainer {
     }
 
     async fn unpause(&self) -> Result<()> {
-        let mut client = Self::get_client().await?;
+        let mut client = Self::get_client(self.container_id.clone()).await?;
```
Comment (DmitryDodzin) [inline mirrord/agent/src/runtime.rs:205]:
```suggestion
        let mut client = self.get_client(self.container_id.clone()).await?;
```

File: mirrord/agent/src/runtime.rs [hunk 5]
```diff
@@ -131,23 +131,51 @@ pub(crate) struct ContainerdContainer {
...
+    sock_path: impl AsRef<std::path::Path>,
+) -> Result<TasksClient<Channel>> {
+    let channel = connect(sock_path).await?;
+    let mut client = TasksClient::new(channel);
+    let request = GetRequest {
+        container_id,
+        ..Default::default()
+    };
+    let request = with_namespace!(request, DEFAULT_CONTAINERD_NAMESPACE);
+    client.get(request).await?;
```
Comment (DmitryDodzin) [inline mirrord/agent/src/runtime.rs:148]: Will this error always? or should also check `.process.is_some().ok_or(AgentError...)?`

**Review by DmitryDodzin — APPROVED** [review]
