### PR TITLE
change internal proxy timeout from extension

### LINKED ISSUE #1088: Connection to internal proxy times out
### Bug Description

N/A

### Steps to Reproduce

This happens pretty consistently when running a node process in VS Code with a prelaunch build task.

### Backtrace

_No response_

### Relevant Logs

_No response_

### Your operating system and version

N/A

### Local process

N/A

### Local process version

_No response_

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by aviramha**
Closes #1088

### CODE REVIEW

File: mirrord/cli/src/config.rs [hunk 1]
```diff
@@ -250,3 +250,11 @@ pub(super) struct ExtensionExecArgs {
     #[arg(short = 't')]
     pub target: Option<String>,
 }
+
+#[derive(Args, Debug)]
+pub(super) struct InternalProxyArgs {
+    /// Launch timeout until we get first connection.
+    /// If layer doesn't connect in this time, we timeout and exit.
+    #[arg(short = 't', default_value_t = 2)]
```
Comment (DmitryDodzin) [inline mirrord/cli/src/config.rs:258]: Probably long should still be here
```suggestion
    #[arg(short = 't', long, default_value_t = 2)]
```

**Review by DmitryDodzin — APPROVED** [review]

File: mirrord/cli/src/config.rs (hunk 1 above)
Comment (aviramha) [reply mirrord/cli/src/config.rs:258]: This isn't used by the outside so I don't see a reason to add it..
