### PR TITLE
Fix running binaries with entitlements on macOS

### LINKED ISSUE #3184: pgrep crash on latest version (macOS)
### Bug Description

running pgrep from mirrord context leads to crash, I suspect it's due to our new signing method. 

### Steps to Reproduce

`mirrord exec pgrep`

### Backtrace

```shell
Binary Images:
       0x2050dc000 -        0x205167fff dyld_path_missing (*) <f2913392-361a-304f-b30d-486be5639e2d> /dyld_path_missing
    0x7ff7ffc91000 -     0x7ff7ffcc0fff main_executable_path_missing (*) <11b18945-107e-3e0d-91fa-b5d5ada3c0c4> /main_executable_path_missing
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???

Error Formulating Crash Report:
dyld_process_snapshot_get_shared_cache failed
PC register does not match crashing frame (0x0 vs 0x7FF7FFC93F7C)

EOF
```

### mirrord layer logs

```shell

```

### mirrord intproxy logs

```shell

```

### mirrord agent logs

```shell

```

### mirrord config

```json

```

### mirrord CLI version

_No response_

### mirrord-agent version

_No response_

### mirrord-operator version (if relevant)

_No response_

### plugin kind and version (if relevant)

_No response_

### Your operating system and version

15.3.1 (24D70)

### Local process

pgrep

### Local process version

_No response_

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by t4lz**
Fix #3184 

Recently the method of signing SIP-patched binaries on macOS was changed, and apparently the library that is now used has a different default behaviour than the cli tool used before.

When re-signing with the CLI, any existing entitlements are cleared. When signing with the library, they remain, unless overwritten with a plist passed in xml format.

Since the patched binary was no longer signed by the entity that was granted those entitlements, the signature was invalid and the process was killed by `taskgated`.

So in order to clear any entitlements the binary might have, we set a constant xml plist that contains an empty entitlement dict.

In addition, we also change the identifier, as the codesign man page says we should, to my understanding.

I'll also add a small unit test for the case of a binary with entitlements, but since this is urgent, it will be in a different PR, to not delay the release of the fix.

### CODE REVIEW

File: mirrord/sip/src/codesign.rs [hunk 1]
```diff
@@ -1,10 +1,31 @@
...
+/// N is the length of the string to generate. If N is odd, the length will be N-1.
+fn generate_hex_string<const N: usize>() -> String {
+    let mut rng = rand::rng();
+    (0..N / 2) // N/2 bytes = N hexadecimal digits.
+        .fold(String::new(), |mut acc, _next_in_range| {
+            // ignoring result: writing to String can't fail.
+            let _ = write!(acc, "{:02x}", rng.random::<u8>());
+            acc
+        })
+}
```
Comment (Razz4780) [inline mirrord/sip/src/codesign.rs:22]: This is kinda weird, we have `hex` :eyes:

File: mirrord/sip/src/codesign.rs [hunk 2]
```diff
@@ -13,10 +34,25 @@ pub(crate) fn sign<PI: AsRef<Path>, PO: AsRef<Path>>(input: PI, output: PO) -> R
...
     // opting into the hardened runtime, which strips away DYLD_INSERT_LIBRARIES etc.
     settings.set_code_signature_flags(SettingsScope::Main, CodeSignatureFlags::ADHOC);
+
+    // `man codesign`:
+    // > It is a **very bad idea** to sign different programs with the same identifier.
+    settings.set_binary_identifier(
+        SettingsScope::Main,
+        bin_id_prefix.map_or_else(
+            || format!("mirrord-patched-bin-{}", generate_hex_string::<40>()),
+            |prefix| format!("{}-{}", prefix, generate_hex_string::<40>()),
```
Comment (Razz4780) [inline mirrord/sip/src/codesign.rs:49]: Kinda worried about [this](https://docs.rs/apple-codesign/0.29.0/apple_codesign/struct.SigningSettings.html#method.set_binary_identifier) - `The binary identifier should be a DNS-like name and should uniquely identify the binary. e.g. com.example.my_program`. The file name might contain invalid characters. Can we always use `mirrord.patched.bin.{hex}`?

Comment (t4lz) [reply mirrord/sip/src/codesign.rs]: Changed in https://github.com/metalbear-co/mirrord/pull/3192/commits/a18d819e82a3f659c2a868788b02b583337fd7b1

**Review by Razz4780 — APPROVED** [review]
🚀 🌔
