### PR TITLE
Error analytics

### LINKED ISSUE #1785: Change analytics to be sent for failed sessions
Currently we only send analytics if we managed to start a session, but we'd like to know when we fail to create a session as well.

### PR DESCRIPTION
**Pull request by DmitryDodzin**
closes #1785

### Summary by CodeRabbit

- New Feature: Introduced `AnalyticsReporter` for collecting and reporting analytics data, enhancing the ability to track both successful runs and errors.
- Refactor: Updated various functions across multiple modules (`connection.rs`, `execution.rs`, `extension.rs`, `internal_proxy.rs`, `main.rs`) to accept an `AnalyticsReporter` object, improving modularity and maintainability.
- New Feature: Added error tracking in the execution process, allowing for better understanding and debugging of runtime issues.
- Refactor: Extracted process execution logic into a new function `exec_process` in `main.rs`, improving code readability and maintainability.

### CODE REVIEW

File: mirrord/cli/src/extension.rs [hunk 1]
```diff
@@ -28,19 +29,38 @@ pub(crate) async fn extension_exec(args: ExtensionExecArgs) -> Result<()> {
...
-    // We don't execute so set envs aren't passed, so we need to add config file and target to env.
-    execution_info.environment.extend(env);
-
-    let output = serde_json::to_string(&execution_info)?;
-    progress.success(Some(&output));
-    execution_info.wait().await?;
-    Ok(())
+    let mut analytics = AnalyticsReporter::new(config.telemetry);
+
+    let execution_result = async {
```
Comment (aviramha) [inline mirrord/cli/src/extension.rs:34]: this pattern is ugly tbh, put it in another function maybe?

File: mirrord/cli/src/execution.rs [hunk 2]
```diff
@@ -182,6 +143,65 @@ impl MirrordExecution {
         })
     }
 
+    async fn fetch_env_vars(
```
Comment (aviramha) [inline mirrord/cli/src/execution.rs:146]: Docs

File: mirrord/cli/src/extension.rs [hunk 3]
```diff
@@ -1,46 +1,80 @@
 use std::collections::HashMap;
 
+use mirrord_analytics::{AnalyticsError, AnalyticsReporter};
 use mirrord_config::LayerConfig;
 use mirrord_progress::{JsonProgress, Progress, ProgressTracker};
 
 use crate::{config::ExtensionExecArgs, error::CliError, execution::MirrordExecution, Result};
 
+async fn mirrord_exec<P>(
```
Comment (aviramha) [inline mirrord/cli/src/extension.rs:9]: docs

**Review by aviramha — APPROVED** [review]
Looks good. Few nitpicks
