### PR TITLE
Mirrord connection reconnect

### LINKED ISSUE #2901: Proxy randomly closes during connection
### Bug Description

After a properly established connection, sometimes I notice the following error pops out of nowhere:
```
Proxy error, connectivity issue or a bug.
                    Please report it to us on https://github.com/metalbear-co/mirrord/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml
                    You can find the `mirrord-intproxy` logs in /tmp/mirrord.log.
                    connection closed
```

` /tmp/mirrod.logs`:
```
  2024-11-06T18:35:27.624023Z  INFO mirrord_intproxy::layer_initializer: new session, process_info: ProcessInfo { pid: 73153, name: "node", cmdline: ["/Users/tyler/.volta/tools/image/node/20.11.1/bin/node", "--enable-source-maps", "--inspect", "/Users/tyler/voiceflow/platform/apps/runtime/build/main"], loaded: true }
    at mirrord/intproxy/src/layer_initializer.rs:63

  2024-11-06T18:42:14.387598Z  WARN mirrord_kube::api::kubernetes::portforwarder: finished retry strategy, closing connection, connect_info: AgentKubernetesConnectInfo { pod_name: "mirrord-agent-wk5eyjv6hc-vllzt", agent_port: 44128, namespace: Some("dev-tyler"), agent_version: Some("3.122.1") }
    at mirrord/kube/src/api/kubernetes/portforwarder.rs:172

  2024-11-06T18:42:14.395494Z ERROR mirrord_intproxy::agent_conn: failed to receive message from the agent, inner task down
    at mirrord/intproxy/src/agent_conn.rs:226

  2024-11-06T18:42:14.396023Z ERROR mirrord_intproxy: task AGENT_CONNECTION failed: agent unexpectedly closed connection
    at mirrord/intproxy/src/lib.rs:243

  2024-11-06T18:42:14.396986Z ERROR mirrord::internal_proxy: Internal proxy encountered an error, exiting, error: Main internal proxy logic failed: agent unexpectedly closed connection
    at mirrord/cli/src/internal_proxy.rs:146
```

### Steps to Reproduce

N/A hard to reproduce but happens randomly

### Backtrace

_No response_

### mirrord layer logs

_No response_

### mirrord intproxy logs

_No response_

### mirrord agent logs

_No response_

### mirrord config

_No response_

### mirrord CLI version

mirrord 3.122.1

### mirrord-agent version

ghcr.io/metalbear-co/mirrord:3.122.1

### mirrord-operator version (if relevant)

_No response_

### plugin kind and version (if relevant)

_No response_

### Your operating system and version

OSx Sonoma 14.4.1

### Local process

nodeJS

### Local process version

nodeJS v20.11.1

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by DmitryDodzin**
Add reconnect option for operator to fix #2901

### CODE REVIEW

File: mirrord/intproxy/src/proxies/incoming/tcp_proxy.rs [hunk 1]
```diff
@@ -41,7 +41,7 @@ pub enum LocalTcpConnection {
 #[derive(Debug)]
 pub struct TcpProxyTask {
     /// The local connection between this task and the user application.
-    connection: LocalTcpConnection,
+    connection: Option<LocalTcpConnection>,
```
Comment (gememma) [inline mirrord/intproxy/src/proxies/incoming/tcp_proxy.rs:44]: Why turn this into an option?

File: mirrord/kube/src/api/kubernetes/portforwarder.rs [hunk 2]
```diff
@@ -162,16 +162,21 @@ impl SinglePortForwarder {
...
-                error = error_future.as_mut() => {
+                biased;
 
-                    if retry_strategy.peek().is_none() || error.is_none() {
-                        tracing::warn!(?connect_info, "finished retry strategy, closing connection");
+                error = error_future.as_mut() => {
+                    if let Some(error) = error {
+                        tracing::warn!(?connect_info, %error, "error while performing port-forward");
+                    } else {
+                        tracing::warn!(?connect_info, "connection exited without error");
```
Comment (gememma) [inline mirrord/kube/src/api/kubernetes/portforwarder.rs:171]: Is this log like "yay no error, this seems normal" or more like "wow it exited so hard it couldnt even tell us why"? I'm wondering how this message should be interpreted if you see it while running mirrord 👀

File: mirrord/kube/src/api/kubernetes/portforwarder.rs [hunk 3]
```diff
@@ -162,16 +162,21 @@ impl SinglePortForwarder {
...
 
                         break;
                     }
 
-                    if let Some(error) = error {
-                        tracing::warn!(?connect_info, %error, "error while performing port-forward, retrying");
+                    if retry_strategy.peek().is_none() {
+                        tracing::warn!(?connect_info, "finished retry strategy, closing connection");
```
Comment (gememma) [inline mirrord/kube/src/api/kubernetes/portforwarder.rs:177]: Similar to above, how should this be interpreted?

**Review by gememma — COMMENTED** [review]
Mostly questions for my own understanding, and a couple of bits and pieces :)

File: mirrord/intproxy/src/proxies/incoming/tcp_proxy.rs (hunk 1 above)
Comment (DmitryDodzin) [reply mirrord/intproxy/src/proxies/incoming/tcp_proxy.rs:44]: Because I changed so `run` no longer consumes self and only gets a mut pointer, thus using `Option::take` is the most elegant solution I though about keeping the run logic the same with ownership of `LocalTcpConnection`

File: mirrord/intproxy/src/lib.rs [hunk 4]
```diff
@@ -270,7 +276,7 @@ impl IntProxy {
 
     /// Routes most messages from the agent to the correct background task.
     /// Some messages are handled here.
-    #[tracing::instrument(level = Level::TRACE, skip(self), ret)]
```
[the remark this answers is not in the document]
Comment (DmitryDodzin) [reply mirrord/intproxy/src/lib.rs:273]: well the return value is `()` so I should just replace with `err` instead of removing

File: mirrord/kube/src/api/kubernetes/portforwarder.rs (hunk 2 above)
Comment (DmitryDodzin) [reply mirrord/kube/src/api/kubernetes/portforwarder.rs]: How about now?

**Review by gememma — APPROVED** [review]
noice 🦅

File: mirrord/intproxy/src/background_tasks.rs [hunk 5]
```diff
@@ -37,6 +38,16 @@ impl<T: BackgroundTask> MessageBus<T> {
         }
     }
 
+    /// Cast `&mut MessageBus<T>` as `&mut MessageBus<R>` only if they share the same message types
+    pub fn cast<R>(&mut self) -> &mut MessageBus<R>
```
Comment (Razz4780) [inline mirrord/intproxy/src/background_tasks.rs:42]: This is used only in this module, right? Should be private

**Review by Razz4780 — CHANGES_REQUESTED** [review]
Beyond what's in the comments:

1. I think we need to check if operator supports reconnecting (new operator feature). Otherwise things will get wild.
3. `FilesProxy` is never informed about the reconnect, and it is very stateful (queues expected responses, caches dir entries and file contents). This scares me :eyes: Same applies to the ping pong task.
4. Not that I want to force my idea, but I think we can do sth simpler:
    1. Let the `AgentConn` task fail in peace.
    2. When `IntProxy` picks it up, it enters a resetting state. It notifies all relevant tasks with a new message variant (e.g `Reset`). Then, it makes a new agent connection and starts a new `AgentConn` task. For each task that was sent a `Reset`, `IntProxy` memorizes that it expects one more `ResetAck` from it.
    3. When a task gets the `Reset` command, it immediately responds with `ResetAck`. Then it does all necessary housekeeping, like cleaning state, sending error responses to the layer (for requests in progress), resending port subscriptions to the agent, dropping local connections, resetting ping pong state.
    5. Intproxy ignores all messages from a resettable task until it gets expected count of `ResetAck`s.
    6. Due to layer storing remote file descriptors, we'd have to create an independent mapping in the `FilesProxy` and make sure not to let through any requests for unknown remote fds.
    7. If it doesn't do that yet, `BackgroundTasks` should remove the task's receiver from the streammap when this task exits (in order to drop all previous messages)

Let me know what you think 'bout this

File: mirrord/intproxy/src/proxies/incoming.rs [hunk 6]
```diff
@@ -533,6 +534,22 @@ impl IncomingProxy {
             IncomingProxyMessage::AgentProtocolVersion(version) => {
                 self.response_mode = ResponseMode::from(&version);
             }
+
+            IncomingProxyMessage::ConnectionRefresh => {
+                let running_task_ids = self.tasks.tasks_ids().cloned().collect::<Vec<_>>();
+
+                for task in running_task_ids {
+                    self.tasks.kill_task(task).await;
+                }
```
[the remark this answers is not in the document]
Comment (DmitryDodzin) [reply mirrord/intproxy/src/proxies/incoming.rs]: Yep, changed to clear function

File: mirrord/intproxy/src/proxies/incoming.rs [hunk 7]
```diff
@@ -533,6 +534,22 @@ impl IncomingProxy {
...
+
+                for subscription in self.subscriptions.iter_mut() {
+                    tracing::debug!(?subscription, "resubscribing");
+
+                    for message in subscription.resubscribe() {
+                        message_bus.send(ProxyMessage::ToAgent(message)).await
+                    }
+                }
```
[the remark this answers is not in the document]
Comment (DmitryDodzin) [reply mirrord/intproxy/src/proxies/incoming.rs]: Well this is assuming that all agent side connections are dead thus we need someone to ask the agent to perform the subscription again so user's app isn't required to re-listen on incoming socket (like intproxy will just recreate the incoming tasks with new listens results)

[the remark this answers is not in the document]
Comment (Razz4780) [reply mirrord/intproxy/src/proxies/incoming.rs]: Yeah yeah that's correct. I only wonder what will happen in the intproxy when it receives a response for a port subscription it considers to have already been confirmed.

File: mirrord/intproxy/src/lib.rs [hunk 8]
```diff
@@ -403,4 +433,58 @@ impl IntProxy {
...
         Ok(())
     }
+
+    #[tracing::instrument(level = Level::TRACE, skip(self), err)]
+    async fn handle_connection_refresh(
+        &mut self,
+        kind: ConnectionRefresh,
+    ) -> Result<(), IntProxyError> {
+        match kind {
+            ConnectionRefresh::Start => {
```
Comment (Razz4780) [inline mirrord/intproxy/src/lib.rs:443]: What if the `PingPong` task fails while the agent connection is dead?

**Review by Razz4780 — CHANGES_REQUESTED** [review]

File: mirrord/intproxy/src/lib.rs [hunk 9]
```diff
@@ -403,4 +433,58 @@ impl IntProxy {
...
+                Box::pin(async {
+                    for msg in task_queue {
+                        tracing::debug!(?msg, "dequeueing message for reconnect");
+
+                        self.handle(msg).await?
+                    }
+
+                    Ok::<(), IntProxyError>(())
+                })
+                .await?
```
[the remark this answers is not in the document]
Comment (DmitryDodzin) [reply mirrord/intproxy/src/lib.rs:484]: Oh recursive rust thing

File: mirrord/intproxy/src/agent_conn.rs [hunk 10]
```diff
@@ -30,14 +29,26 @@ use tokio::{
...
+    main_tasks::{ConnectionRefresh, ProxyMessage},
 };
 
+mod portforward;
+
+static OPERATOR_RETRY_VERSION: LazyLock<VersionReq> = LazyLock::new(|| {
+    ">3.104.2"
+        .parse()
+        .expect("OPERATOR_RETRY_VERSION should be a valid VersionReq value")
+});
```
[the remark this answers is not in the document]
Comment (DmitryDodzin) [reply mirrord/intproxy/src/agent_conn.rs:50]: I feel conflicted about it because technically it's just a bugfix for operator and not quite a new feature, I think I should merge the operator pr and then after release, I can do it the regular operator way but technically operator should not be aware of reconnect (like it should be similar to fork behaviour)

File: mirrord/intproxy/src/proxies/incoming.rs (hunk 7 above)
[the remark this answers is not in the document]
Comment (DmitryDodzin) [reply mirrord/intproxy/src/proxies/incoming.rs]: It fails thus I must reset the state of all subscriptions to non confirmed and because of that resubscribe requires mutable ref to subscription as well, maybe the name can be more clear like `reset_and_resubscrive_message`

File: mirrord/intproxy/src/agent_conn.rs [hunk 11]
```diff
@@ -30,14 +29,26 @@ use tokio::{
...
+    main_tasks::{ConnectionRefresh, ProxyMessage},
 };
 
+mod portforward;
+
+static OPERATOR_RETRY_VERSION: LazyLock<VersionReq> = LazyLock::new(|| {
+    ">3.105.0"
+        .parse()
+        .expect("OPERATOR_RETRY_VERSION should be a valid VersionReq value")
+});
```
Comment (Razz4780) [inline mirrord/intproxy/src/agent_conn.rs:50]: I'd rather stick to using operator features for consistency. Also, we might release new operator before the counterpart is merged, so this check might become invalid

File: mirrord/intproxy/src/proxies/simple.rs [hunk 12]
```diff
@@ -58,14 +59,19 @@ impl SimpleProxy {
             .as_ref()
             .is_some_and(|version| ADDRINFO_V2_VERSION.matches(version))
     }
+
+    fn handle_connection_refresh(&mut self) {
+        self.addr_info_reqs.clear();
+        self.get_env_reqs.clear();
+    }
```
Comment (Razz4780) [inline mirrord/intproxy/src/proxies/simple.rs:66]: Gotta flush error responses, no? :eyes:

File: mirrord/intproxy/src/proxies/outgoing.rs [hunk 13]
```diff
@@ -220,21 +220,28 @@ impl OutgoingProxy {
         let msg = request.protocol.wrap_agent_connect(request.remote_address);
         message_bus.send(ProxyMessage::ToAgent(msg)).await;
     }
+
+    async fn handle_connection_refresh(&mut self) {
+        self.datagrams_reqs.clear();
+        self.stream_reqs.clear();
+        self.txs.clear();
+    }
```
Comment (Razz4780) [inline mirrord/intproxy/src/proxies/outgoing.rs:228]: Gotta flush error responses

**Review by Razz4780 — CHANGES_REQUESTED** [review]
The last batch

File: mirrord/intproxy/src/proxies/simple.rs (hunk 12 above)
Comment (DmitryDodzin) [reply mirrord/intproxy/src/proxies/simple.rs]: This only happens on startup but sure I added everywhere

**Review by Razz4780 — APPROVED** [review]
🔥
