### PR TITLE
Fallible Operator Discover

### LINKED ISSUE #1218: make finding operator fallible
In some cases, where trying to connect to operator fails because it's not really there, or lack of permissions to even check that cause an error mirrord fails and forces the user to mention to not use operator.
Instead of this behavior, we should just issue a warning and continue without using the operator.

### PR DESCRIPTION
**Pull request by DmitryDodzin**
closes #1218

### CODE REVIEW

File: changelog.d/1218.fixed.md [hunk 1]
```diff
@@ -0,0 +1,2 @@
+mirrord-cli: update cli so failute to connect to operator will try operatorless flow instead of exiting
```
Comment (eyalb181) [inline changelog.d/1218.fixed.md:1]:
```suggestion
mirrord-cli: update cli so failure to connect to operator will try operatorless flow instead of exiting
```

Comment (aviramha) [inline changelog.d/1218.fixed.md:1]: update cli so failing to use operator will fallback to no-operator mode.

**Review by eyalb181 — APPROVED** [review]
