### PR TITLE
Don't filter outgoing traffic to target

### LINKED ISSUE #2572: Outgoing connections to same service are not stolen
### Bug Description

1. Application steals from port 8081
2. Makes a request to its own k8s service
3. Agent makes outgoing connection
4. The connection should be stolen by the same agent, but it's not 

### Steps to Reproduce

---

### Backtrace

_No response_

### Relevant Logs

_No response_

### Your operating system and version

---

### Local process

---

### Local process version

_No response_

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by DmitryDodzin**
Updated so if requests comes from target address don't fliter them out in our OUTPUT chain

closes #2572

### CODE REVIEW

File: mirrord/agent/src/steal/ip_tables/output.rs [hunk 1]
```diff
@@ -23,18 +21,13 @@ where
     pub fn create(ipt: Arc<IPT>, chain_name: String) -> Result<Self> {
         let managed = IPTableChain::create(ipt, chain_name)?;
 
-        let gid = getgid();
-        managed
-            .add_rule(&format!("-m owner --gid-owner {gid} -p tcp -j RETURN"))
-            .inspect_err(|_| {
-                warn!("Unable to create iptable rule with \"--gid-owner {gid}\" filter")
-            })?;
+        managed.add_rule("! -o lo -j RETURN")?;
```
Comment (Razz4780) [inline mirrord/agent/src/steal/ip_tables/output.rs:24]: This change combined with changes to `add_redirect`/`remove_redirect` are a noop, right?

**Review by Razz4780 — COMMENTED** [review]
How can it possibly work without filtering by gid? :eyes:

File: mirrord/agent/src/steal/ip_tables/output.rs (hunk 1 above)
Comment (DmitryDodzin) [reply mirrord/agent/src/steal/ip_tables/output.rs:24]: Yes this should result in same result

File: mirrord/agent/src/steal/ip_tables/output.rs [hunk 2]
```diff
@@ -20,12 +20,18 @@ where
 {
     const ENTRYPOINT: &'static str = "OUTPUT";
 
-    pub fn create(ipt: Arc<IPT>, chain_name: String) -> Result<Self> {
+    pub fn create(ipt: Arc<IPT>, chain_name: String, pod_ips: Option<&str>) -> Result<Self> {
         let managed = IPTableChain::create(ipt, chain_name)?;
 
+        let exclude_source_ips = pod_ips
+            .map(|pod_ips| format!("! -s {pod_ips}"))
+            .unwrap_or_default();
```
Comment (Razz4780) [inline mirrord/agent/src/steal/ip_tables/output.rs:28]: Wait, so the complete rule is now like "ignore TCP packets sent from agent's GID, unless they're sent from pod's IPs"? How does it help? Isn't this part a noop? :eyes:

Comment (DmitryDodzin) [reply mirrord/agent/src/steal/ip_tables/output.rs:28]: Not quite because the outgoing handler runs in the target process namespace so the request do originate from the agent (checking what happens on ephemerals)

**Review by aviramha — CHANGES_REQUESTED** [review]

File: mirrord/agent/src/cli.rs [hunk 3]
```diff
@@ -41,6 +41,9 @@ pub struct Args {
     /// If not given, the agent will not use TLS.
     #[arg(long, env = AGENT_OPERATOR_CERT_ENV)]
     pub operator_tls_cert_pem: Option<String>,
+
+    #[arg(long)]
+    pub pod_ips: Option<String>,
```
[the remark this answers is not in the document]
Comment (DmitryDodzin) [reply mirrord/agent/src/cli.rs]: updated, should be fine now

File: mirrord/agent/src/steal/ip_tables/output.rs (hunk 2 above)
Comment (DmitryDodzin) [reply mirrord/agent/src/steal/ip_tables/output.rs:28]: ephemeral agent works just fine

**Review by aviramha — APPROVED** [review]
Approving changes requested by me - still need additional approval.

**Review by Razz4780 — APPROVED** [review]
LGTM ^^
