### PR TITLE
Fix agent crash on sniffer failure

### LINKED ISSUE #2909: mirrord fails when sniffer fails on old kernel
was supposed to be fixed in 3.124.1 thanks to https://github.com/metalbear-co/mirrord/pull/2897 but apparently not

### PR DESCRIPTION
**Pull request by aviramha**
Closes #2909

### CODE REVIEW

File: mirrord/agent/src/entrypoint.rs [hunk 1]
```diff
@@ -514,7 +514,7 @@ async fn start_agent(args: Args) -> Result<()> {
     } else {
         let cancellation_token = cancellation_token.clone();
         let is_mesh = args.is_mesh();
-
+        let (sniffer_init_tx, sniffer_init_rx) = tokio::sync::oneshot::channel::<bool>();
```
Comment (meowjesty) [inline mirrord/agent/src/entrypoint.rs:517]:
```suggestion
        // We're using this to avoid crashing on old kernels when initializing the `RawSocketTcpCapture`.
        let (sniffer_init_tx, sniffer_init_rx) = tokio::sync::oneshot::channel::<bool>();
```
