### PR TITLE
change env to use container runtime env instead of proc environ

### LINKED ISSUE #1135: Environment variables are not mapped
### Bug Description

It seems that given https://mirrord.dev/docs/reference/env/ we should get the targeted Pod's environment variables but when running `mirror exec ...` I get only local env.

My original use cases runs an operator which needs k8s related host and port envs:

```
error creating inClusterConfig, falling back to default config: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
```

but running `bash` or `env` yields similar results.

### Steps to Reproduce

1. Run
  
  ```
  MIRRORD_AGENT_RUST_LOG=trace RUST_LOG=debug mirrord exec --no-telemetry --target-namespace ns --target pod/$(k get pod -n ns -l...) env
  ```

2. Observe local env being printed

### Backtrace

_No response_

### Relevant Logs

```shell
2023-02-28T14:11:48.723636Z DEBUG hyper::proto::h1::conn: incoming body is content-length (19 bytes)
2023-02-28T14:11:48.723645Z DEBUG hyper::proto::h1::conn: incoming body completed
2023-02-28T14:11:48.723656Z DEBUG HTTP{http.method=GET http.url=https://127.0.0.1:62756/apis/operator.metalbear.co/v1/namespaces/kong-system/targets/pod.kong-kong-676fdd4664-q6sqr otel.name="get" otel.kind="client"}: hyper::client::pool: pooling idle connection for ("https", 127.0.0.1:62756)
2023-02-28T14:11:48.723692Z  WARN kube_client::client: Unsuccessful data error parse: 404 page not found

2023-02-28T14:11:48.723697Z DEBUG kube_client::client: Unsuccessful: ErrorResponse { status: "404 Not Found", message: "\"404 page not found\\n\"", reason: "Failed to parse error data", code: 404 } (reconstruct)
...
28T14:09:56.947984Z DEBUG HTTP{http.method=GET http.url=https://127.0.0.1:62756/api/v1/namespaces/default/pods/mirrord-agent-tas84wid30-xmww2/portforward?&ports=60500 otel.name="HTTP" otel.kind="client"}: kube_client::client::builder: requesting
2023-02-28T14:09:56.948043Z DEBUG HTTP{http.method=GET http.url=https://127.0.0.1:62756/api/v1/namespaces/default/pods/mirrord-agent-tas84wid30-xmww2/portforward?&ports=60500 otel.name="HTTP" otel.kind="client"}: hyper::client::connect::http: connecting to 127.0.0.1:62756
2023-02-28T14:09:56.948177Z DEBUG HTTP{http.method=GET http.url=https://127.0.0.1:62756/api/v1/namespaces/default/pods/mirrord-agent-tas84wid30-xmww2/portforward?&ports=60500 otel.name="HTTP" otel.kind="client"}: hyper::client::connect::http: connected to 127.0.0.1:62756
2023-02-28T14:09:56.948189Z DEBUG HTTP{http.method=GET http.url=https://127.0.0.1:62756/api/v1/namespaces/default/pods/mirrord-agent-tas84wid30-xmww2/portforward?&ports=60500 otel.name="HTTP" otel.kind="client"}: rustls::client::hs: No cached session for IpAddress(127.0.0.1)
2023-02-28T14:09:56.948221Z DEBUG HTTP{http.method=GET http.url=https://127.0.0.1:62756/api/v1/namespaces/default/pods/mirrord-agent-tas84wid30-xmww2/portforward?&ports=60500 otel.name="HTTP" otel.kind="client"}: rustls::client::hs: Not resuming any session
2023-02-28T14:09:56.950699Z DEBUG HTTP{http.method=GET http.url=https://127.0.0.1:62756/api/v1/namespaces/default/pods/mirrord-agent-tas84wid30-xmww2/portforward?&ports=60500 otel.name="HTTP" otel.kind="client"}: rustls::client::hs: Using ciphersuite TLS13_AES_128_GCM_SHA256
2023-02-28T14:09:56.950708Z DEBUG HTTP{http.method=GET http.url=https://127.0.0.1:62756/api/v1/namespaces/default/pods/mirrord-agent-tas84wid30-xmww2/portforward?&ports=60500 otel.name="HTTP" otel.kind="client"}: rustls::client::tls13: Not resuming
2023-02-28T14:09:56.950762Z DEBUG HTTP{http.method=GET http.url=https://127.0.0.1:62756/api/v1/namespaces/default/pods/mirrord-agent-tas84wid30-xmww2/portforward?&ports=60500 otel.name="HTTP" otel.kind="client"}: rustls::client::tls13: TLS1.3 encrypted extensions: []
2023-02-28T14:09:56.950766Z DEBUG HTTP{http.method=GET http.url=https://127.0.0.1:62756/api/v1/namespaces/default/pods/mirrord-agent-tas84wid30-xmww2/portforward?&ports=60500 otel.name="HTTP" otel.kind="client"}: rustls::client::hs: ALPN protocol is None
2023-02-28T14:09:56.950775Z DEBUG HTTP{http.method=GET http.url=https://127.0.0.1:62756/api/v1/namespaces/default/pods/mirrord-agent-tas84wid30-xmww2/portforward?&ports=60500 otel.name="HTTP" otel.kind="client"}: rustls::client::tls13: Got CertificateRequest CertificateRequestPayloadTLS13 { context: , extensions: [Unknown(UnknownExtension { typ: StatusRequest, payload:  }), Unknown(UnknownExtension { typ: SCT, payload:  }), SignatureAlgorithms([RSA_PSS_SHA256, ECDSA_NISTP256_SHA256, ED25519, RSA_PSS_SHA384, RSA_PSS_SHA512, RSA_PKCS1_SHA256, RSA_PKCS1_SHA384, RSA_PKCS1_SHA512, ECDSA_NISTP384_SHA384, ECDSA_NISTP521_SHA512, RSA_PKCS1_SHA1, ECDSA_SHA1_Legacy]), AuthorityNames([3015311330110603550403130a6b756265726e65746573, 3019311730150603550403130e66726f6e742d70726f78792d6361])] }
2023-02-28T14:09:56.950784Z DEBUG HTTP{http.method=GET http.url=https://127.0.0.1:62756/api/v1/namespaces/default/pods/mirrord-agent-tas84wid30-xmww2/portforward?&ports=60500 otel.name="HTTP" otel.kind="client"}: rustls::client::common: Attempting client auth
2023-02-28T14:09:56.951695Z DEBUG hyper::proto::h1::io: flushed 283 bytes
2023-02-28T14:09:56.952210Z DEBUG rustls::client::tls13: Ticket saved
2023-02-28T14:09:56.959914Z DEBUG hyper::proto::h1::io: parsed 4 headers
2023-02-28T14:09:56.959929Z DEBUG hyper::proto::h1::conn: incoming body is empty
2023-02-28T14:09:57.019817Z  INFO ThreadId(01) mirrord_layer::error: libc error (doesn't indicate a problem) >> ResponseError(
    RemoteIO(
        RemoteIOError {
            raw_os_error: Some(
                2,
            ),
            kind: NotFound,
        },
    ),
)

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
bash-3.2$
```

### Your operating system and version

MacOS 13.2.1

### Local process

Any

### Local process version

_No response_

### Additional Info

k8s v1.26.0
go 1.20.1

### PR DESCRIPTION
**Pull request by aviramha**
Fixes #1135

### CODE REVIEW

File: mirrord/agent/src/env.rs [hunk 1]
```diff
@@ -52,43 +48,23 @@ impl EnvFilter {
...
-        .filter_map(
-            |mut keys_and_values| match (keys_and_values.pop(), keys_and_values.pop()) {
-                (Some(value), Some(key)) => Some((key.to_string(), value.to_string())),
-                _ => None,
-            },
-        )
+    let env_vars = full_env
+        .iter()
         .filter(|(key, _)| env_filter.matches(key))
+        .map(|(a, b)| (a.clone(), b.clone()))
```
Comment (DmitryDodzin) [inline mirrord/agent/src/env.rs:67]:
```suggestion
        .cloned()
```

**Review by t4lz — COMMENTED** [review]
not done reviewing

File: mirrord/agent/src/runtime.rs [hunk 2]
```diff
@@ -171,30 +214,55 @@ impl ContainerdContainer {
...
+        let mut client = self.get_task_client().await?;
         let container_id = self.container_id.to_string();
         let request = GetRequest {
             container_id,
             ..Default::default()
         };
         let request = with_namespace!(request, DEFAULT_CONTAINERD_NAMESPACE);
-        let response = client.get(request).await?;
+        let response = client.get(request).await?.into_inner();
         let pid = response
```
Comment (t4lz) [inline mirrord/agent/src/runtime.rs:240]:
```suggestion
        let pid = client.get(request).await?.into_inner()
```
I think we don't need to keep `response` as an intermediate value here, right? but this is nitpicky and completely optional.

File: mirrord/agent/src/runtime.rs [hunk 3]
```diff
@@ -171,30 +214,55 @@ impl ContainerdContainer {
...
 
-        Ok(pid as u64)
+        let mut client = self.get_container_client().await?;
+        let request = GetContainerRequest {
+            id: self.container_id.to_string(),
+        };
+        let request = with_namespace!(request, DEFAULT_CONTAINERD_NAMESPACE);
+        let response = client.get(request).await?.into_inner();
+
+        let spec: Spec = response
```
Comment (t4lz) [inline mirrord/agent/src/runtime.rs:252]:
```suggestion
        let spec: Spec = client.get(request).await?.into_inner()
```
Same here

File: mirrord/agent/src/env.rs [hunk 4]
```diff
@@ -52,43 +48,23 @@ impl EnvFilter {
...
 /// requested from `mirrord-layer` (ignores vars specified in `filter_env_vars`).
-///
-/// Returns an error if none of the requested environment variables were found.
-pub async fn select_env_vars(
-    environ_path: PathBuf,
+pub(crate) fn select_env_vars(
+    full_env: &HashMap<String, String>,
     filter_env_vars: HashSet<String>,
     select_env_vars: HashSet<String>,
 ) -> RemoteResult<HashMap<String, String>> {
```
[the remark this answers is not in the document]
Comment (aviramha) [reply mirrord/agent/src/env.rs:55]: not sure if it's worth breaking the protocol for this

File: mirrord/agent/src/runtime.rs [hunk 5]
```diff
@@ -137,24 +161,43 @@ pub(crate) struct ContainerdContainer {
...
+/// Translate ToIter<String> of "K=V" to HashMap.
+fn parse_raw_env<'a, T: IntoIterator<Item = &'a String>>(raw: T) -> HashMap<String, String> {
+    raw.into_iter()
+        .map(|key_and_value| key_and_value.splitn(2, '=').collect::<Vec<_>>())
+        // [["DB", "foo.db"], ["PORT", "99"], ["HOST"], ["PATH", "/fake"]]
+        .filter_map(
+            |mut keys_and_values| match (keys_and_values.pop(), keys_and_values.pop()) {
+                (Some(value), Some(key)) => Some((key.to_string(), value.to_string())),
+                _ => None,
+            },
```
Comment (t4lz) [inline mirrord/agent/src/runtime.rs:185]: What do you think about something like this:
```suggestion
        .map(|key_and_value| key_and_value.splitn(2, '='))
        // [["DB", "foo.db"], ["PORT", "99"], ["HOST"], ["PATH", "/fake"]]
        .map(|pair_iter| (pair_iter.next(), pair_iter.next()))
        .filter(|(key, value)| value.is_some())
```

File: mirrord/agent/src/env.rs (hunk 4 above)
[the remark this answers is not in the document]
Comment (t4lz) [reply mirrord/agent/src/env.rs:55]: Ever, or right now? Should we maybe add a comment here and at the protocol definition that this is a relic?

File: mirrord/agent/src/main.rs [hunk 6]
```diff
@@ -446,7 +444,11 @@ async fn start_agent() -> Result<()> {
     .await?;
 
     let mut state = State::new(&args).await?;
-    let pid = state.get_container_pid().await?;
+    let (pid, env) = match state.get_container_info().await? {
```
Comment (t4lz) [inline mirrord/agent/src/main.rs:447]: This`?` now means the agent exits if it can't get the environment variables, right? Before it would return a remote error to the client, but wouldn't exit directly because of it. Just making sure this change is intentional.

**Review by t4lz — APPROVED** [review]
Left some comments, they're all up to you, so you can resolve them and merge if you want.

File: mirrord/agent/src/env.rs (hunk 1 above)
Comment (aviramha) [reply mirrord/agent/src/env.rs:67]: I think I tried and it doesn't work, will try again.

Comment (aviramha) [reply mirrord/agent/src/env.rs:67]: yeah, doesn't work

File: mirrord/agent/src/runtime.rs (hunk 5 above)
Comment (aviramha) [reply mirrord/agent/src/runtime.rs:185]: it makes the pair_iter `Option<K>, Option<V>` afaik

File: mirrord/agent/src/main.rs (hunk 6 above)
Comment (aviramha) [reply mirrord/agent/src/main.rs:447]: yeah but if the error occurred the layer would die anyway so don't think it's a massive change. also there's no reason for it to fail

File: mirrord/agent/src/env.rs (hunk 4 above)
[the remark this answers is not in the document]
Comment (aviramha) [reply mirrord/agent/src/env.rs:57]: done
