### PR TITLE
fix go environment variables injection, issue #292

### LINKED ISSUE #292: Go programs cannot access environment variables
### Bug Description

Go binaries cannot access environment variables.

### Steps to Reproduce

```go
// main.go
package main

import (
	"fmt"
	"os"
)

func main() {
	fmt.Println(os.Environ())
}
```

```shell
go build main.go
```

```shell
mirrord exec \
        --pod-namespace some-namespace \
        --pod-name some-pod \
        --override-env-vars-include "*" \
        ./main
```

Compare with

```shell
mirrord exec \
        --pod-namespace some-namespace \
        --pod-name some-pod \
        --override-env-vars-include "*" \
        env
```

### Backtrace

_No response_

### Relevant Logs

_No response_

### Your operating system and version

macOS 12.5.1 Monterey

### Local process

main: Mach-O 64-bit executable x86_64
go version go1.19 darwin/amd64

### Local process version

_No response_

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by aviramha**
closes #292

### CODE REVIEW

File: mirrord-layer/src/go_env.rs [hunk 1]
```diff
@@ -0,0 +1,62 @@
...
+        argv.push(CString::new(arg).unwrap().into_raw());
+    }
+    argv.push(std::ptr::null_mut());
+
+    // Add environment variables to our new argv
+    for (key, value) in std::env::vars() {
+        argv.push(CString::new(format!("{key}={value}")).unwrap().into_raw());
+    }
+
+    argv.push(std::ptr::null_mut());
```
Comment (meowjesty) [inline mirrord-layer/src/go_env.rs:34]: Do we need to add `null` twice to `argv`?

**Review by meowjesty — APPROVED** [review]
👀
