### PR TITLE
fix mirroring not handling big requests #1178

### LINKED ISSUE #1178: Panics when request JSON payload is big
### Bug Description

I have a service that receives a lot of data, sometime json with a size of more than 1.5Mb, in such cases mirrord panics and exits.

### Steps to Reproduce

1. Create a python fastapi app that can listen to POST requests.
2. Send it 1.5Mb of JSON.
3. Run mirrord locally and point it to the pod as a target, and execute the same app with it locally.
4. You should see that it panics and exits for big payloads.

### Backtrace

```shell
RUST_BACKTRACE=full mirrord exec --target pod/stats-lib-7f68b5c7b9-gpzqv uvicorn stats:app

⠹ mirrord cli starting
  ✓ ready to launch process
  ✓ layer extracted
  ✓ agent pod created
  ✓ pod is ready
INFO:     Started server process [265562]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
2023-03-08T22:00:31.163670Z ERROR ThreadId(15) mirrord_layer::connection: agent disconnected    
2023-03-08T22:00:31.163904Z ERROR ThreadId(15) mirrord_layer: agent connection lost
mirrord has encountered an error and is now exiting.
thread 'tokio-runtime-worker' panicked at 'explicit panic', mirrord/layer/src/lib.rs:764:5
stack backtrace:
   0:     0x7eff6629d7ca - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h73c35c4801b724ca
   1:     0x7eff662c43be - core::fmt::write::h8c363f5140091876
   2:     0x7eff66298275 - std::io::Write::write_fmt::h8c16a1bf1becaaee
   3:     0x7eff6629d595 - std::sys_common::backtrace::print::h2918040dd65cef95
   4:     0x7eff6629ed7f - std::panicking::default_hook::{{closure}}::h5341f57db0d4eac9
   5:     0x7eff6629eabb - std::panicking::default_hook::h5100ba7bc8f5c260
   6:     0x7eff6629f489 - std::panicking::rust_panic_with_hook::h24a4486effe6aca0
   7:     0x7eff6629f1e2 - std::panicking::begin_panic_handler::{{closure}}::h381e6d2317fbd244
   8:     0x7eff6629dc7c - std::sys_common::backtrace::__rust_end_short_backtrace::h8de60f5213da11fe
   9:     0x7eff6629ef32 - rust_begin_unwind
  10:     0x7eff658ef6b3 - core::panicking::panic_fmt::hfb1f7bbba2d7c980
  11:     0x7eff658ef74d - core::panicking::panic::h1b8bb9aa36d28b0e
  12:     0x7eff65b0a6d4 - mirrord_layer::thread_loop::{{closure}}::h53edfca7c8a6cd1c
  13:     0x7eff6591d3e3 - tokio::runtime::task::core::Core<T,S>::poll::{{closure}}::he47a57e37ffc14e4
  14:     0x7eff65b73c8b - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::haa47370590236c4e
  15:     0x7eff6591abfa - tokio::runtime::task::core::Core<T,S>::poll::h4db3ac2b0b09826e
  16:     0x7eff65bb96a4 - tokio::runtime::task::harness::poll_future::{{closure}}::ha211b9c75790ac56
  17:     0x7eff658f2236 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h5b9e70a10c658201
  18:     0x7eff65b8d429 - std::panicking::try::do_call::h90209217afa539bb
  19:     0x7eff65b917fb - __rust_try
  20:     0x7eff65b899a3 - std::panicking::try::h9535804c5f610bf7
  21:     0x7eff65ba5f6d - std::panic::catch_unwind::h25bd888651815af6
  22:     0x7eff65bb3dfb - tokio::runtime::task::harness::poll_future::h0d41f83c64165e3e
  23:     0x7eff65bbce31 - tokio::runtime::task::harness::Harness<T,S>::poll_inner::hf74d3e8e25c1987d
  24:     0x7eff65bc11f3 - tokio::runtime::task::harness::Harness<T,S>::poll::h3a4e206fdc41785e
  25:     0x7eff65ad834e - tokio::runtime::task::raw::poll::h81a822859b46efc5
  26:     0x7eff6606479c - tokio::runtime::task::raw::RawTask::poll::h70d14622a02ab4d1
  27:     0x7eff65ffb735 - tokio::runtime::task::LocalNotified<S>::run::h85d6974987ef8fad
  28:     0x7eff660433a1 - tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}::h96a714717241f7a1
  29:     0x7eff66042dfe - tokio::runtime::scheduler::multi_thread::worker::Context::run_task::ha4c53835715e29ac
  30:     0x7eff66042531 - tokio::runtime::scheduler::multi_thread::worker::Context::run::h54c633b1234b11f8
  31:     0x7eff660422fd - tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}::h3e8d02f1711ee089
INFO:     Shutting down
  32:     0x7eff66033a2a - tokio::macros::scoped_tls::ScopedKey<T>::set::h1a5b3fe090062910
  33:     0x7eff6604220e - tokio::runtime::scheduler::multi_thread::worker::run::hedbb52a65090b832
  34:     0x7eff66041fb7 - tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}::h59a1b899ed2d0d5c
  35:     0x7eff65ff3bc4 - <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll::heb527e693e5b21ad
  36:     0x7eff66013fc9 - tokio::runtime::task::core::Core<T,S>::poll::{{closure}}::h06844eaff7fc04a9
  37:     0x7eff6601ad4b - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::h7c720185deb99580
  38:     0x7eff66013eee - tokio::runtime::task::core::Core<T,S>::poll::h75e305962138f896
  39:     0x7eff66054548 - tokio::runtime::task::harness::poll_future::{{closure}}::hac583eff5849cde6
  40:     0x7eff65ff89f6 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h22ae84bcfe7bcb4a
  41:     0x7eff6602469a - std::panicking::try::do_call::h5e4cfe9d49380fb5
  42:     0x7eff6602843b - __rust_try
  43:     0x7eff66023773 - std::panicking::try::h1918d150a606f916
  44:     0x7eff6602342e - std::panic::catch_unwind::h735a059af8ccc32d
  45:     0x7eff66053bbc - tokio::runtime::task::harness::poll_future::h3a479c454920b227
  46:     0x7eff66051c6f - tokio::runtime::task::harness::Harness<T,S>::poll_inner::hb2bea3a613c32eaf
  47:     0x7eff66051727 - tokio::runtime::task::harness::Harness<T,S>::poll::h606990aabb4dd2a6
  48:     0x7eff660648d0 - tokio::runtime::task::raw::poll::he7915e839bbee6a9
  49:     0x7eff6606479c - tokio::runtime::task::raw::RawTask::poll::h70d14622a02ab4d1
  50:     0x7eff65ffb7ed - tokio::runtime::task::UnownedTask<S>::run::h63e2d841df057252
  51:     0x7eff660549e6 - tokio::runtime::blocking::pool::Task::run::hffbdd25f734def89
  52:     0x7eff6605806f - tokio::runtime::blocking::pool::Inner::run::hdeefc47cc7047e25
  53:     0x7eff660575e4 - tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}::h5d1e286b7f250601
  54:     0x7eff66016d41 - std::sys_common::backtrace::__rust_begin_short_backtrace::h1cac25629d7c7e6b
  55:     0x7eff66047db2 - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::ha1b360bd48a47ebf
  56:     0x7eff65ff8b02 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h9cfd9c76f14ec7c8
  57:     0x7eff66024c71 - std::panicking::try::do_call::hfe80b70dd8b91b41
  58:     0x7eff6602843b - __rust_try
  59:     0x7eff66024276 - std::panicking::try::hc51df123d49de36d
  60:     0x7eff66023330 - std::panic::catch_unwind::h414e5c2ca060b91c
  61:     0x7eff66047b7f - std::thread::Builder::spawn_unchecked_::{{closure}}::h6707df874b31d873
  62:     0x7eff66038467 - core::ops::function::FnOnce::call_once{{vtable.shim}}::ha96080cd51d12f3c
  63:     0x7eff662a41b3 - std::sys::unix::thread::Thread::new::thread_start::hb4fdede19f04b2fa
  64:     0x7eff650ae12d - start_thread
  65:     0x7eff6512fbc0 - clone3
  66:                0x0 - <unknown>
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [265562]
```

### Relevant Logs

_No response_

### Your operating system and version

Linux

### Local process

uvicorn

### Local process version

_No response_

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by aviramha**
fixes #1178

### CODE REVIEW

File: mirrord/agent/src/main.rs [hunk 1]
```diff
@@ -467,17 +467,27 @@ async fn start_agent() -> Result<()> {
...
 
     let stealer_cancellation_token = cancellation_token.clone();
     let stealer_task = run_thread_in_namespace(
-        TcpConnectionStealer::new(stealer_command_rx)
-            .and_then(|stealer| stealer.start(stealer_cancellation_token)),
+        TcpConnectionStealer::new(stealer_command_rx).and_then(|stealer| async move {
+            if let Err(err) = stealer.start(stealer_cancellation_token).await {
+                error!("Stealer failed: {err}");
+            }
+            Ok(())
```
Comment (DmitryDodzin) [inline mirrord/agent/src/main.rs:489]:
```suggestion
        TcpConnectionStealer::new(stealer_command_rx).map_ok(|stealer| async move {
            if let Err(err) = stealer.start(stealer_cancellation_token).await {
                error!("Stealer failed: {err}");
            }
```

File: mirrord/agent/src/main.rs [hunk 2]
```diff
@@ -467,17 +467,27 @@ async fn start_agent() -> Result<()> {
...
     let sniffer_cancellation_token = cancellation_token.clone();
     let sniffer_task = run_thread_in_namespace(
-        TcpConnectionSniffer::new(sniffer_command_rx, args.network_interface)
-            .and_then(|sniffer| sniffer.start(sniffer_cancellation_token)),
+        TcpConnectionSniffer::new(sniffer_command_rx, args.network_interface).and_then(
+            |sniffer| async move {
+                if let Err(err) = sniffer.start(sniffer_cancellation_token).await {
+                    error!("Sniffer failed: {err}");
+                }
+                Ok(())
```
Comment (DmitryDodzin) [inline mirrord/agent/src/main.rs:475]:
```suggestion
        TcpConnectionSniffer::new(sniffer_command_rx, args.network_interface).map_ok(
            |sniffer| async move {
                if let Err(err) = sniffer.start(sniffer_cancellation_token).await {
                    error!("Sniffer failed: {err}");
                }
```

**Review by DmitryDodzin — APPROVED** [review]
Nitpick
