### PR TITLE
fix turbo + mirrord

### LINKED ISSUE #2500: npm module not found when running turbo app
### Bug Description

Getting module not found when running some npm applications.

Seems like it could be related to #1956 and #1957, as we're getting the same error.

What is happening is that node is looking for module in a location that is relative to a path in our temp dir, but we want it to look for modules relative to the original path.
Not sure why our protections for that (hooking `_NSGetExecutablePath`, passing non-patched paths in exec args) did not prevent this. Maybe now the exec path is retrieved in a different way.

Volta-installed node is SIP-protected, unlike most node installations we've seen so far. I think this might be related to this issue.

### Steps to Reproduce

```
git clone git@github.com:t4lz/mirrord-sip-npm-issue.git
```
```
cd mirrord-sip-npm-issue
```
you might have to install vollta and then install npm and npx via vollta at this point.
```
npm run repro
```

### Backtrace

```shell
│ node:internal/modules/cjs/loader:1148
│   throw err;
│   ^
│ 
│ Error: Cannot find module '../lib/cli.js'
│ Require stack:
│ - /private/var/folders/4l/810mmn597cx7zy5w2bk11clh0000gn/T/mirrord-bin/Users/tal/.volta/tools/image/node/20.14.0/bin/npm
│     at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
│     at Module._load (node:internal/modules/cjs/loader:986:27)
│     at Module.require (node:internal/modules/cjs/loader:1233:19)
│     at require (node:internal/modules/helpers:179:18)
│     at Object.<anonymous> (/private/var/folders/4l/810mmn597cx7zy5w2bk11clh0000gn/T/mirrord-bin/Users/tal/.volta/tools/image/node/20.14.0/bin/npm:2:1)
│     at Module._compile (node:internal/modules/cjs/loader:1358:14)
│     at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
│     at Module.load (node:internal/modules/cjs/loader:1208:32)
│     at Module._load (node:internal/modules/cjs/loader:1024:12)
│     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12) {
│   code: 'MODULE_NOT_FOUND',
│   requireStack: [
│     '/private/var/folders/4l/810mmn597cx7zy5w2bk11clh0000gn/T/mirrord-bin/Users/tal/.volta/tools/image/node/20.14.0/bin/npm'
│   ]
│ }
│ 
│ Node.js v20.14.0
└────>
┌ web#dev > cache bypass, force executing acec579587217658 
│ 2024-06-06T17:55:53.106830Z TRACE ThreadId(16) mirrord_layer::file::hooks: path Success(
│     "/dev/fd",
│ ) | open_options OpenOptionsInternal {
│     read: true,
│     write: false,
│     append: false,
│     truncate: false,
│     create: false,
│     create_new: false,
│ }
│ 2024-06-06T17:55:53.106950Z TRACE ThreadId(16) mirrord_layer::exec_utils: Executable /Users/tal/Documents/projects/test_projects/volta_test/my-turborepo/node_modules/turbo-darwin-arm64/bin/turbo called execve/posix_spawn
│ 2024-06-06T17:55:53.107190Z TRACE ThreadId(16) mirrord_sip::main: Using existing SIP-patched version of "/usr/bin/env": "/var/folders/4l/810mmn597cx7zy5w2bk11clh0000gn/T/mirrord-bin/usr/bin/env"
│ 2024-06-06T17:55:53.107199Z TRACE ThreadId(16) mirrord_sip::main: Shebang points to: "/usr/bin/env". Patching the interpreter and making a version of "/Users/tal/.volta/tools/image/node/20.14.0/bin/npm" with an altered shebang 
│ at: "/var/folders/4l/810mmn597cx7zy5w2bk11clh0000gn/T/mirrord-bin/Users/tal/.volta/tools/image/node/20.14.0/bin/npm"
│ 2024-06-06T17:55:53.107328Z TRACE ThreadId(16) mirrord_layer::exec_utils: exec arg: /Users/tal/.volta/tools/image/node/20.14.0/bin/npm
│ 2024-06-06T17:55:53.107331Z TRACE ThreadId(16) mirrord_layer::exec_utils: exec arg: run
│ 2024-06-06T17:55:53.107333Z TRACE ThreadId(16) mirrord_layer::exec_utils: exec arg: dev
│ node:internal/modules/cjs/loader:1148
│   throw err;
│   ^
│ 
│ Error: Cannot find module '../lib/cli.js'
│ Require stack:
│ - /private/var/folders/4l/810mmn597cx7zy5w2bk11clh0000gn/T/mirrord-bin/Users/tal/.volta/tools/image/node/20.14.0/bin/npm
│     at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
│     at Module._load (node:internal/modules/cjs/loader:986:27)
│     at Module.require (node:internal/modules/cjs/loader:1233:19)
│     at require (node:internal/modules/helpers:179:18)
│     at Object.<anonymous> (/private/var/folders/4l/810mmn597cx7zy5w2bk11clh0000gn/T/mirrord-bin/Users/tal/.volta/tools/image/node/20.14.0/bin/npm:2:1)
│     at Module._compile (node:internal/modules/cjs/loader:1358:14)
│     at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
│     at Module.load (node:internal/modules/cjs/loader:1208:32)
│     at Module._load (node:internal/modules/cjs/loader:1024:12)
│     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12) {
│   code: 'MODULE_NOT_FOUND',
│   requireStack: [
│     '/private/var/folders/4l/810mmn597cx7zy5w2bk11clh0000gn/T/mirrord-bin/Users/tal/.volta/tools/image/node/20.14.0/bin/npm'
│   ]
│ }
│ 
│ Node.js v20.14.0
│ command finished with error: command (/Users/tal/Documents/projects/test_projects/volta_test/my-turborepo/apps/web) /Users/tal/.volta/tools/image/node/20.14.0/bin/npm run dev exited (1)
└────>
 ERROR  run failed: command  exited (1)
```

### Relevant Logs

```shell
│ 2024-06-06T17:55:53.105024Z TRACE ThreadId(15) mirrord_layer::exec_utils: Executable /Users/tal/Documents/projects/test_projects/volta_test/my-turborepo/node_modules/turbo-darwin-arm64/bin/turbo called execve/posix_spawn
│ 2024-06-06T17:55:53.105276Z TRACE ThreadId(15) mirrord_sip::main: Using existing SIP-patched version of "/usr/bin/env": "/var/folders/4l/810mmn597cx7zy5w2bk11clh0000gn/T/mirrord-bin/usr/bin/env"
│ 2024-06-06T17:55:53.105289Z TRACE ThreadId(15) mirrord_sip::main: Shebang points to: "/usr/bin/env". Patching the interpreter and making a version of "/Users/tal/.volta/tools/image/node/20.14.0/bin/npm" with an altered shebang 
│ at: "/var/folders/4l/810mmn597cx7zy5w2bk11clh0000gn/T/mirrord-bin/Users/tal/.volta/tools/image/node/20.14.0/bin/npm"
│ 2024-06-06T17:55:53.105867Z TRACE ThreadId(15) mirrord_layer::exec_utils: exec arg: /Users/tal/.volta/tools/image/node/20.14.0/bin/npm
│ 2024-06-06T17:55:53.105872Z TRACE ThreadId(15) mirrord_layer::exec_utils: exec arg: run
│ 2024-06-06T17:55:53.105874Z TRACE ThreadId(15) mirrord_layer::exec_utils: exec arg: dev
```

### Your operating system and version

MacOS 14.5

### Local process

npm, node, turbo

### Local process version

_No response_

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by aviramha**
Closes #2500

### CODE REVIEW

File: mirrord/cli/src/execution.rs [hunk 1]
```diff
@@ -162,9 +162,12 @@ impl MirrordExecution {
         if let Ok(v) = std::env::var(INJECTION_ENV_VAR) {
             env_vars.insert(INJECTION_ENV_VAR.to_string(), format!("{v}:{lib_path}"))
         } else {
-            env_vars.insert(INJECTION_ENV_VAR.to_string(), lib_path)
+            env_vars.insert(INJECTION_ENV_VAR.to_string(), lib_path.clone())
         };
 
+        // for use in execvp (restoring library path)
+        env_vars.insert("MIRRORD_LIBRARY_PATH".to_string(), lib_path);
```
Comment (t4lz) [inline mirrord/cli/src/execution.rs:169]: Is `MIRRORD_LIBRARY_PATH` used anywhere? If not I think we can undo the changes to this file.

File: mirrord/layer/src/exec_utils.rs [hunk 2]
```diff
@@ -171,14 +171,40 @@ fn intercept_tmp_dir(argv_arr: &Nul<*const c_char>) -> Detour<Argv> {
     Success(c_string_vec)
 }
 
+/// Verifies that mirrord environment is passed to child process
+fn intercept_environment(envp_arr: &Nul<*const c_char>) -> Detour<Argv> {
+    let mut c_string_vec = Argv::default();
+
+    let mut found_dyld = false;
+    for arg in envp_arr.iter() {
+        let arg_str: &str = arg.checked_into()?;
```
Comment (t4lz) [inline mirrord/layer/src/exec_utils.rs:180]: I think here instead of returning a `Detour::Bypass` if an env var is not valid UTF-8, we could just add it to `c_string_vec` and `continue` to the next env var, using `let ... else`. This will mean that we can still find the dyld var even if some other var is not a valid UTF-8 string.
The one limitation we would still have is that if for some reason the dyld var's value is not a valid UTF-8 string (not because of our lib, but because of something the user or their tools put in there), we would fail, but I guess that's ok for now?

File: mirrord/layer/src/exec_utils.rs [hunk 3]
```diff
@@ -196,22 +222,27 @@ unsafe fn patch_sip_for_new_process(
...
 ///    path.
 /// 2. argv - we strip mirrord's temporary directory from the start of arguments. So if argv[1] is
 ///    "/var/folders/1337/mirrord-bin/opt/homebrew/bin/npx" Switch it to "/opt/homebrew/bin/npx"
 ///    Also here we create a new array with pointers to new strings, even if there are no changes
 ///    needed (except for the case of an error).
-///
+/// 3. envp - We found out that Turbopack (Vercel) spawns a clean "Node" instance without env,
+///    basically stripping all of the important mirrord env. We restore the env here. https://github.com/metalbear-co/mirrord/issues/2500
+///    EDIT - We don't restore all env, just DYLD as it seems Turbo just strips the env at beginning
+///    and probably doesn't need more than just injecting for SIP.
```
Comment (t4lz) [inline mirrord/layer/src/exec_utils.rs:245]:
```suggestion
/// 3. envp - We found out that Turbopack (Vercel) spawns a clean "Node" instance without env,
///    basically stripping all of the important mirrord env.
///    https://github.com/metalbear-co/mirrord/issues/2500
///    We restore the `DYLD_INSERT_LIBRARIES` environment variable and all env vars starting with `MIRRORD_` if the dyld var can't be found in `envp`.
```

File: mirrord/cli/src/execution.rs (hunk 1 above)
Comment (aviramha) [reply mirrord/cli/src/execution.rs:169]: Nice catch.

File: mirrord/cli/src/execution.rs [hunk 4]
```diff
@@ -162,7 +162,7 @@ impl MirrordExecution {
         if let Ok(v) = std::env::var(INJECTION_ENV_VAR) {
             env_vars.insert(INJECTION_ENV_VAR.to_string(), format!("{v}:{lib_path}"))
         } else {
-            env_vars.insert(INJECTION_ENV_VAR.to_string(), lib_path)
+            env_vars.insert(INJECTION_ENV_VAR.to_string(), lib_path.clone())
```
Comment (t4lz) [inline mirrord/cli/src/execution.rs:165]: no need, right?

File: mirrord/layer/src/exec_utils.rs [hunk 5]
```diff
@@ -171,14 +171,41 @@ fn intercept_tmp_dir(argv_arr: &Nul<*const c_char>) -> Detour<Argv> {
...
 
+/// Verifies that mirrord environment is passed to child process
+fn intercept_environment(envp_arr: &Nul<*const c_char>) -> Detour<Argv> {
+    let mut c_string_vec = Argv::default();
+
+    let mut found_dyld = false;
+    for arg in envp_arr.iter() {
+        let Detour::Success(arg_str): Detour<&str> = arg.checked_into() else {
+            tracing::debug!("Failed to convert envp argument to string. Skipping.");
+            continue;
```
[the remark this answers is not in the document]
Comment (aviramha) [reply mirrord/layer/src/exec_utils.rs:182]: how? we failed to convert it to &str..?

[the remark this answers is not in the document]
Comment (t4lz) [reply mirrord/layer/src/exec_utils.rs:182]: That suggestion code was wrong, but we can do something like this:
```suggestion
            c_string_vec.0.push(CStr::from_ptr(arg).to_owned());
            continue;
```

**Review by t4lz — APPROVED** [review]
