### PR TITLE
Detect Python debugger PyCharm

### LINKED ISSUE #1020: PyCharm debugger can't attach
### Bug Description

When using PyCharm with debugger, PyCharm can't connect to the debugee's listening port.
`/home/user/PycharmProjects/pythonProject/venv/bin/python /opt/pycharm-professional/plugins/python/helpers/pydev/pydevd.py --module --multiprocess --qt-support=auto --client 127.0.0.1 --port 36141 --file flask run --port=5000 `

error: 
`Could not connect to 127.0.0.1: 36141`

### Steps to Reproduce

pycharm run debugger with flask

### Backtrace

_No response_

### Relevant Logs

_No response_

### Your operating system and version

Linux

### Local process

Python

### Local process version

_No response_

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by Razz4780**
Fixes #1020 

Added new `DebuggerType` variant for PyDevD used by PyCharm.

Also fixed `:runIde` command for PyCharm Community and Ultimate

### CODE REVIEW

File: mirrord/layer/src/debugger_ports.rs [hunk 1]
```diff
@@ -33,34 +57,47 @@ impl FromStr for DebuggerType {
     fn from_str(s: &str) -> Result<Self, Self::Err> {
         match s {
```
Comment (aviramha) [inline mirrord/layer/src/debugger_ports.rs:58]: looking at this PR, I think we shouldn't have a variant for each `DebuggerType` since the detection and port extracting logic is quite similar and repeated..
A good question would be why not have the enum's impl as a standalone function that just returns port to ignore? holding the variant doens't help us anyway?

Comment (aviramha) [reply mirrord/layer/src/debugger_ports.rs:58]: to be more concrete - I am afraid that the detection here is too "lite" while just trying to extract the port is way more full

Comment (Razz4780) [reply mirrord/layer/src/debugger_ports.rs:58]: > to be more concrete - I am afraid that the detection here is too "lite" while just trying to extract the port is way more full

I'm not sure if I follow. When we use this feature we know exactly which debugger is used.

Comment (aviramha) [reply mirrord/layer/src/debugger_ports.rs:58]: I am saying we shouldn't split the logic into "detection" and "extraction" - just try to extract and if it fails fallback to env port and if that is missing/fails don't ignore anything.

Comment (aviramha) [reply mirrord/layer/src/debugger_ports.rs:58]: instead of 
```rs
let debugger_type = "pydevd".parse()
let ignore_port = debugger_type.get_port()
```
do
```rs
let ignore_port = get_debugger_ignore_port()

fn get_debugge_ignore_port() -> Option<u16> {    
  if python {
        if pydevd {}
        else if otherthingy {}
        else { envport}
    } else { envport} 
}

Comment (Razz4780) [reply mirrord/layer/src/debugger_ports.rs:58]: Hmm, this detection thing was added having a specific case in mind - when the debuggers are invoked by the IDEs and the users have no way to select the port themselves. If the user has control over the port selection, I'd rather leave it up to them to explicitly ignore it in the config (or not, if that is their use case). But if you think this would improve UX, I can change it

Comment (Razz4780) [reply mirrord/layer/src/debugger_ports.rs:58]: Resolving after a call :heavy_check_mark:

**Review by aviramha — APPROVED** [review]

**Comment by aviramha** [comment]
Great work!
