### PR TITLE
fix environment regression by mixing the two approaches together.

### LINKED ISSUE #1180: Environment variables regression
We are using [Bank-Vaults mutating webhook](https://banzaicloud.com/docs/bank-vaults/mutating-webhook/) to inject env variables, and this setup works with mirrord 3.29.0 but not with 3.30.0 - the target is an Alpine-based container, and I can see them in `/proc/1/environ`. Perhaps a combination of the two approaches is needed?

_Originally posted by @artem-collectai in https://github.com/metalbear-co/mirrord/issues/1135#issuecomment-1464072811_

### PR DESCRIPTION
**Pull request by aviramha**
Fixes #1180

### CODE REVIEW

**Review by DmitryDodzin — APPROVED** [review]

File: mirrord/agent/src/env.rs [hunk 1]
```diff
@@ -46,23 +51,46 @@ impl EnvFilter {
...
+    Ok(parse_raw_env(raw_env_vars.split_terminator(char::from(0))))
+}
+
 /// Helper function that loads the process' environment variables, and selects only those that were
 /// requested from `mirrord-layer` (ignores vars specified in `filter_env_vars`).
 ///
 /// NOTE: can remove `RemoteResult` when we break protocol compatibility.
-pub(crate) fn select_env_vars(
+#[tracing::instrument(level = "trace", skip(full_env))]
+pub(crate) async fn select_env_vars(
```
Comment (DmitryDodzin) [inline mirrord/agent/src/env.rs:88]: No need async I think

Comment (aviramha) [reply mirrord/agent/src/env.rs:88]: nice catch! thanks
