### PR TITLE
Block ipv6 binds to prevent C# errors

### LINKED ISSUE #1121: C# Support
Simple example given here https://github.com/aeb-dev/mirrord-test doesn't work with mirrord.
```
The AddressFamily InterNetwork is not valid for the System.Net.IPEndPoint end point, use InterNetworkV6 instead. (Parameter socketAddress)
```

### PR DESCRIPTION
**Pull request by DmitryDodzin**
closes #1121

### CODE REVIEW

**Comment by aviramha** [comment]
CHANGELOG :)

**Review by aviramha — CHANGES_REQUESTED** [review]

File: mirrord/layer/src/error.rs [hunk 1]
```diff
@@ -193,6 +196,9 @@ impl From<HookError> for i64 {
             HookError::IO(ref e) if (is_ignored_code(e.raw_os_error())) => {
                 info!("libc error (doesn't indicate a problem) >> {:#?}", fail)
             }
+            HookError::SocketUnsuportedIpv6 => {
+                info!("{}", fail)
```
Comment (aviramha) [inline mirrord/layer/src/error.rs:200]: `info!("{fail}")`

**Review by aviramha — APPROVED** [review]
nitpick but can merge :)
