### PR TITLE
fix wsl config with IntelliJ

### LINKED ISSUE #1210: JetBrains WSL doesn't work with config file
log:
```
creating command line and executing C:\Windows\system32\wsl.exe [--distribution, Ubuntu-22.04, --exec, /bin/sh, -c, /mnt/c/Users/U/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/223.8836.41.plugins/mirrord/bin/linux/x86-64/mirrord ls -o json -f 'E:\marosa\workspace\plain-report-service\.mirrord\mirrord.json']
```

as can be seen, the issue is that we don't convert the path to a WSL one.

### PR DESCRIPTION
**Pull request by aviramha**
Fix #1210

### CODE REVIEW

File: intellij-ext/modules/core/src/main/kotlin/com/metalbear/mirrord/MirrordApi.kt [hunk 1]
```diff
@@ -49,10 +49,14 @@ object MirrordApi {
     fun listPods(configFile: String?, project: Project?, wslDistribution: WSLDistribution?): List<String> {
         MirrordLogger.logger.debug("listing pods")
         var commandLine = GeneralCommandLine(cliPath(wslDistribution), "ls", "-o", "json")
-        configFile?.let {
+        configFile?.let {config ->
             MirrordLogger.logger.debug("adding configFile to command line")
             commandLine.addParameter("-f")
-            commandLine.addParameter(it)
+            wslDistribution?.let {
+                commandLine.addParameter(it.getWslPath(config) ?: config)
```
Comment (eyalb181) [inline intellij-ext/modules/core/src/main/kotlin/com/metalbear/mirrord/MirrordApi.kt:56]: Are both options valid?

Comment (aviramha) [reply intellij-ext/modules/core/src/main/kotlin/com/metalbear/mirrord/MirrordApi.kt:56]: no but I think it's a worthy fallback - my concern that path is already `WSL'd` for some reason and that's why it didn't work, hence fallback

Comment (aviramha) [reply intellij-ext/modules/core/src/main/kotlin/com/metalbear/mirrord/MirrordApi.kt:56]: added clarification

**Review by eyalb181 — APPROVED** [review]
