### PR TITLE
Clarify exceptions in FS config docs

### LINKED ISSUE #2020: Clarify exceptions in FS config docs

### PR DESCRIPTION
**Pull request by t4lz**
closes #2020

### CODE REVIEW

File: mirrord/config/src/feature/fs/advanced.rs [hunk 1]
```diff
@@ -19,6 +19,9 @@ use crate::{
 /// 3. `"local"` - Read from the local file system.
 /// 5. `"disable"` - Disable file operations.
```
Comment (eyalb181) [inline mirrord/config/src/feature/fs/advanced.rs:20]: I think we're missing number 4 here? Is it localwithoverrides?

File: mirrord/config/src/feature/fs/advanced.rs [hunk 2]
```diff
@@ -19,6 +19,9 @@ use crate::{
...
 ///
+/// > Note: There are pre-defined exceptions to the mode, so some paths will be read locally by
```
Comment (eyalb181) [inline mirrord/config/src/feature/fs/advanced.rs:22]:
```suggestion
/// > Note: by default, some specific paths are read locally or remotely, regardless of the selected FS mode. This is described in further detail below.
```

File: mirrord/config/src/feature/fs/advanced.rs [hunk 3]
```diff
@@ -37,8 +40,22 @@ use crate::{
...
+/// 2. There are pre-defined exceptions to the set FS mode.
+///   a. Paths that match
+///      [the patterns defined here](https://github.com/metalbear-co/mirrord/tree/latest/mirrord/layer/src/file/filter/read_local_by_default.rs)
+///      are read locally by default.
+///   b. Paths that match
+///      [the patterns defined here](https://github.com/metalbear-co/mirrord/tree/latest/mirrord/layer/src/file/filter/read_remote_by_default.rs)
+///      are read remotely by default when the mode is `localwithoverrides`.
+///   c. Paths that match
+///      [the patterns defined here](https://github.com/metalbear-co/mirrord/tree/latest/mirrord/layer/src/file/filter/not_found_by_default.rs)
+///      under the running user's home directory will be failed to be found by default when the mode
```
Comment (eyalb181) [inline mirrord/config/src/feature/fs/advanced.rs:52]:
```suggestion
///      under the running user's home directory will not be found by the application when the mode
```

File: mirrord/config/src/feature/fs/advanced.rs [hunk 4]
```diff
@@ -37,8 +40,22 @@ use crate::{
...
+///      is not `local`.
+/// In order to override that default setting for a path, or a pattern, include it the appropriate
```
Comment (eyalb181) [inline mirrord/config/src/feature/fs/advanced.rs:54]: How do you override the "not found" list? Maybe it's better to add an example of how to override to each list, rather than a general example at the bottom.

**Review by eyalb181 — CHANGES_REQUESTED** [review]

File: mirrord/config/src/feature/fs/advanced.rs (hunk 1 above)
Comment (t4lz) [reply mirrord/config/src/feature/fs/advanced.rs:20]: I think you're right. Also, I don't think there is a `disable` mode.
```suggestion
/// 4. `"localwithoverrides"` - perform fs operation locally, unless the path matches a pre-defined or user-specified exception.
```

File: mirrord/config/src/feature/fs/advanced.rs (hunk 4 above)
Comment (t4lz) [reply mirrord/config/src/feature/fs/advanced.rs:54]: You have to include a path in another list that specifies what should happen with it - `read_only`/`read_write`/`local`.
I'm afraid if I make this text any longer no one will ever read it.

**Review by eyalb181 — APPROVED** [review]
