### PR TITLE
Iptables PREROUTING fallback

### LINKED ISSUE #1640: agent crashes on steal
Error
```
Iptables failed with `code: 1, msg: Warning: Extension owner revision 0 not supported, missing kernel module?
iptables: No chain/target/match by that name
```

Pretty sure it's linked either to #1615 or #1527 
suspecting #1527 more heavily - I'm assuming we use a match that is available only on newer kernels

### PR DESCRIPTION
**Pull request by DmitryDodzin**
closes #1640

### CODE REVIEW

**Review by eyalb181 — CHANGES_REQUESTED** [review]

File: mirrord/agent/src/steal/ip_tables/standard.rs [hunk 1]
```diff
@@ -29,7 +30,17 @@ where
         let own_packet_filter = "-o lo".to_owned();
 
         let gid = getgid();
-        managed.add_rule(&format!("-m owner --gid-owner {gid} -p tcp -j RETURN"))?;
+        if let Err(err) = managed.add_rule(&format!("-m owner --gid-owner {gid} -p tcp -j RETURN"))
+        {
+            warn!("Uable to create iptable rule with --gid-owner filter trying with --pid-owner: {err}");
```
Comment (eyalb181) [inline mirrord/agent/src/steal/ip_tables/standard.rs]:
```suggestion
            warn!("Unable to create iptable rule with --gid-owner filter trying with --pid-owner: {err}");
```

File: mirrord/agent/src/steal/ip_tables.rs [hunk 2]
```diff
@@ -134,7 +136,16 @@ where
         let mut redirect = if let Some(vendor) = MeshVendor::detect(&ipt)? {
             Redirects::Mesh(MeshRedirect::create(Arc::new(ipt), vendor)?)
         } else {
-            Redirects::Standard(StandardRedirect::create(Arc::new(ipt))?)
+            let ipt = Arc::new(ipt);
+
+            match StandardRedirect::create(ipt.clone()) {
+                Err(err) => {
+                    warn!("Uable to create StandardRedirect chain: {err}");
```
Comment (eyalb181) [inline mirrord/agent/src/steal/ip_tables.rs:143]:
```suggestion
                    warn!("Unable to create StandardRedirect chain: {err}");
```

File: mirrord/agent/src/steal/ip_tables.rs [hunk 3]
```diff
@@ -150,7 +161,16 @@ where
         let mut redirect = if let Some(vendor) = MeshVendor::detect(&ipt)? {
             Redirects::Mesh(MeshRedirect::load(Arc::new(ipt), vendor)?)
         } else {
-            Redirects::Standard(StandardRedirect::load(Arc::new(ipt))?)
+            let ipt = Arc::new(ipt);
+
+            match StandardRedirect::load(ipt.clone()) {
+                Err(err) => {
+                    warn!("Uable to load StandardRedirect chain: {err}");
```
Comment (eyalb181) [inline mirrord/agent/src/steal/ip_tables.rs:168]:
```suggestion
                    warn!("Unable to load StandardRedirect chain: {err}");
```

File: mirrord/agent/src/steal/ip_tables/standard.rs [hunk 4]
```diff
@@ -29,7 +30,11 @@ where
         let own_packet_filter = "-o lo".to_owned();
 
         let gid = getgid();
-        managed.add_rule(&format!("-m owner --gid-owner {gid} -p tcp -j RETURN"))?;
+        managed
+            .add_rule(&format!("-m owner --gid-owner {gid} -p tcp -j RETURN"))
+            .inspect_err(|_| {
+                warn!("Uable to create iptable rule with \"--gid-owner {gid}\" filter")
```
Comment (eyalb181) [inline mirrord/agent/src/steal/ip_tables/standard.rs:36]:
```suggestion
                warn!("Unable to create iptable rule with \"--gid-owner {gid}\" filter")
```

**Review by eyalb181 — CHANGES_REQUESTED** [review]

**Review by eyalb181 — APPROVED** [review]
