### PR TITLE
Framed Http Request/Response

### LINKED ISSUE #1731: GRPC steal with filter error
### Bug Description

Error when stealing on with `http_filter` set to filter by the selected ports and all requests start failing
```
command call: rpc error: code = Internal desc = server closed the stream without sending trailers
```

### Steps to Reproduce

1. deploy dexidp (or any other go grpc api)
2. mirrord exec evans -- -r --host dex --port 5557 (or any other)
3. mirrord exec -f .mirrord/mirrord.json ./bin/docker-entrypoint -- ./dex serve /etc/dex/config.docker.yaml
4. evans: call GetVersion and see error

### Backtrace

_No response_

### Relevant Logs

_No response_

### Your operating system and version

macOS 13.5 (22G74)

### Local process

dex (grpc)

### Local process version

_No response_

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by DmitryDodzin**
closes #1731

### CODE REVIEW

File: mirrord/agent/src/main.rs [hunk 1]
```diff
@@ -462,6 +466,14 @@ impl ClientConnectionHandler {
                 ))
                 .await?;
             }
+            ClientMessage::SwitchProtocolVersion(version) => {
+                self.tcp_stealer_api
+                    .switch_protocl_version(version.clone())
```
Comment (aviramha) [inline mirrord/agent/src/main.rs:471]: `protocol`

File: mirrord/operator/src/crd.rs [hunk 2]
```diff
@@ -110,4 +111,6 @@ pub struct LicenseInfoOwned {
 #[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize, JsonSchema)]
 pub enum OperatorFeatures {
     ProxyApi,
+    #[serde(other)]
+    Unknown,
```
Comment (aviramha) [inline mirrord/operator/src/crd.rs:115]: I think this is a good change but belongs in a new PR?

**Review by aviramha — APPROVED** [review]
nitpicks
