### PR TITLE
Istio Ambient Patch

### LINKED ISSUE #2456: Istio Ambient Mesh Compatibility
Mirrord works great with Istio's traditional sidecar deployment mode, and even gives a helpful message about `--steal` when it detects service meshes.

However, I'm not sure if it's a bug or not implemented that mirrord doesn't work with Istio's ambient mode. Is this on the roadmap? The agent pod runs fine but ATM I need to remove a `istio.io/dataplane-mode: ambient` label from the namespace for mirrord to successfully steal traffic.

### PR DESCRIPTION
**Pull request by DmitryDodzin**
closes #2456

Add support to istio with `istio.io/dataplane-mode: ambient`

*Note update does require privileged agent to work.*
```json
{
  "agnet": {
    "privileged": true
  }
}
```

### CODE REVIEW

**Comment by aviramha** [comment]
Can we warn user if we detect ambient mesh and privileged is false?

File: changelog.d/2456.fixed.md [hunk 1]
```diff
@@ -0,0 +1 @@
+Add custom handling for istio ambient mode where we set `/proc/sys/net/ipv4/conf/all/route_localnet` to `1` so it does require `agent.privilated = true` to work. (See [#2456](https://github.com/metalbear-co/mirrord/issues/2456))
```
Comment (aviramha) [inline changelog.d/2456.fixed.md:1]: Typo in privileged

**Comment by DmitryDodzin** [comment]
> Can we warn user if we detect ambient mesh and privileged is false?

It's a bit convoluted currently because we do the final detection in the iptables-guard agent process before any connection is even made but a "hacky" way with env variables is possible

**Comment by aviramha** [comment]
> > Can we warn user if we detect ambient mesh and privileged is false?
> 
> It's a bit convoluted currently because we do the final detection in the iptables-guard agent process before any connection is even made but a "hacky" way with env variables is possible

isn't `MeshVendor` detected as part of runtime, which is created in the cli?

File: mirrord/agent/src/steal/ip_tables/mesh/istio.rs [hunk 2]
```diff
@@ -0,0 +1,92 @@
...
+use crate::{
+    error::Result,
+    steal::ip_tables::{
+        output::OutputRedirect, prerouting::PreroutingRedirect, redirect::Redirect, IPTables,
+        IPTABLE_IPV4_ROUTE_LOCALNET_ORIGINAL, IPTABLE_MESH,
+    },
+};
+
+pub(crate) struct AmbientRedirect<IPT: IPTables> {
+    prerouteing: PreroutingRedirect<IPT>,
```
Comment (Razz4780) [inline mirrord/agent/src/steal/ip_tables/mesh/istio.rs:15]:
```suggestion
    prerouting: PreroutingRedirect<IPT>,
```

**Review by Razz4780 — APPROVED** [review]
Looks good, one typo is field name

**Comment by DmitryDodzin** [comment]
> isn't `MeshVendor` detected as part of runtime, which is created in the cli?

Well it's partially true, we do pass the runtime via cli args but also perform detection inside safe iptables

**Comment by aviramha** [comment]
> > isn't `MeshVendor` detected as part of runtime, which is created in the cli?
> 
> Well it's partially true, we do pass the runtime via cli args but also perform detection inside safe iptables

So let's warn in that case.

File: mirrord/kube/src/api/kubernetes.rs [hunk 3]
```diff
@@ -227,18 +228,31 @@ impl KubernetesAPI {
...
+            progress.info(&format!("service mesh detected: {mesh}"));
+
+            let incoming_mode = config.map(|config| config.feature.network.incoming.mode);
+
+            if matches!(incoming_mode, Some(IncomingMode::Mirror)) {
+                progress.warning(
+                    "mirrord has detected that you might be running on a cluster with a \
+                     service mesh and `network.incoming.mode = \"mirror\"`, which is currently \
+                     unsupported. You can set `network.incoming.mode` to \"steal\" (check out the\
+                     `http_filter` configuration value if you only want to steal some of the traffic).",
```
Comment (Razz4780) [inline mirrord/kube/src/api/kubernetes.rs:241]: Huh, wait. Is this still true? :eyes: 
We even have custom logic in the sniffer when mesh is detected

File: mirrord/kube/src/api/kubernetes.rs [hunk 4]
```diff
@@ -227,18 +228,31 @@ impl KubernetesAPI {
...
+
+                let privileged = config
+                    .map(|config| config.agent.privileged)
+                    .unwrap_or_default();
+
+                if matches!(mesh, MeshVendor::IstioAmbient) && !privileged {
+                    progress.warning(
+                        "mirrord has detected that there is an ambient istio service mesh but\
+                         agent will not be created with a privileged SecurtyContext,\
+                         please set `agent.privileged = true` otherwise agent will not be able to start.",
```
Comment (Razz4780) [inline mirrord/kube/src/api/kubernetes.rs:252]:
```suggestion
                        "mirrord detected an ambient Istio service mesh but\
                         the agent is not configured to run in a privileged SecurityContext.\
                         Please set `agent.privileged = true`, otherwise the agent will not be able to start.",
```

File: mirrord/kube/src/api/container.rs [hunk 5]
```diff
@@ -104,23 +104,26 @@ where
...
+    if pod
+        .metadata
+        .annotations
+        .as_ref()
+        .and_then(|annotations| annotations.get("ambient.istio.io/redirection"))
+        .map(|annotation| annotation == "enabled")
+        .unwrap_or_default()
+    {
+        return Some(MeshVendor::IstioAmbient);
+    }
```
Comment (Razz4780) [inline mirrord/kube/src/api/container.rs:122]: Now that we're actually creating `IstioAmbient` variant and passing it to agent CLI, there's a problem - what if the agent is older and doesn't recognize this variant?

**Review by Razz4780 — CHANGES_REQUESTED** [review]

File: mirrord/kube/src/api/container.rs (hunk 5 above)
Comment (DmitryDodzin) [reply mirrord/kube/src/api/container.rs:122]: I though about it though I'm not sure how to solve it elegantly (also older version of agent won't work properly on mesh proxy anyway no?)

File: mirrord/kube/src/api/kubernetes.rs (hunk 3 above)
Comment (DmitryDodzin) [reply mirrord/kube/src/api/kubernetes.rs]: Yep it works now, I removed it

File: mirrord/kube/src/api/container.rs (hunk 5 above)
Comment (DmitryDodzin) [reply mirrord/kube/src/api/container.rs:122]: Ok I did a compatibility change
