### PR TITLE
Skip iptables cleanup if done already

### LINKED ISSUE #3220: Agent prints bogus warnings
When the agent cleans up iptables (parent process), it prints bogus warnings:
```
mirrord-agent-z6pdr mirrord-agent   2025-03-28T13:52:39.608334Z ERROR mirrord_agent_iptables: error: code: 2, msg: iptables v1.8.9 (legacy): Couldn't load target `MIRRORD_INPUT_nWRUn':No such file or directory
mirrord-agent-z6pdr mirrord-agent 
mirrord-agent-z6pdr mirrord-agent Try `iptables -h' or 'iptables --help' for more information.
mirrord-agent-z6pdr mirrord-agent 
mirrord-agent-z6pdr mirrord-agent     at mirrord/agent/iptables/src/lib.rs:198 on ThreadId(3)
mirrord-agent-z6pdr mirrord-agent 
mirrord-agent-z6pdr mirrord-agent   2025-03-28T13:52:39.608338Z ERROR mirrord_agent_iptables: error: code: 2, msg: iptables v1.8.9 (legacy): Couldn't load target `MIRRORD_INPUT_nWRUn':No such file or directory
mirrord-agent-z6pdr mirrord-agent 
mirrord-agent-z6pdr mirrord-agent Try `iptables -h' or 'iptables --help' for more information.
mirrord-agent-z6pdr mirrord-agent 
mirrord-agent-z6pdr mirrord-agent     at mirrord/agent/iptables/src/lib.rs:318 on ThreadId(3)
mirrord-agent-z6pdr mirrord-agent 
mirrord-agent-z6pdr mirrord-agent   2025-03-28T13:52:39.623587Z ERROR mirrord_agent_iptables: error: code: 1, msg: iptables: No chain/target/match by that name.
mirrord-agent-z6pdr mirrord-agent 
mirrord-agent-z6pdr mirrord-agent     at mirrord/agent/iptables/src/lib.rs:155 on ThreadId(3)
mirrord-agent-z6pdr mirrord-agent 
mirrord-agent-z6pdr mirrord-agent   2025-03-28T13:52:39.624793Z ERROR mirrord_agent_iptables: error: code: 1, msg: iptables: No chain/target/match by that name.
mirrord-agent-z6pdr mirrord-agent 
mirrord-agent-z6pdr mirrord-agent     at mirrord/agent/iptables/src/lib.rs:155 on ThreadId(3)
```

### PR DESCRIPTION
**Pull request by 0x00A5**
Fix #3220

### CODE REVIEW

File: mirrord/agent/src/entrypoint.rs [hunk 1]
```diff
@@ -804,11 +804,19 @@ async fn start_agent(args: Args) -> AgentResult<()> {
...
-    let tables = SafeIpTables::load(IPTablesWrapper::from(ipt), false).await?;
-    tables.cleanup().await?;
+    if !SafeIpTables::list_mirrord_rules(&ipt).await?.is_empty() {
+        let tables = SafeIpTables::load(ipt, false).await?;
+        tables.cleanup().await?;
+    } else {
+        trace!("No mirorrd rules found, skipping iptables cleanup.");
+    }
 
     Ok(())
```
Comment (meowjesty) [inline mirrord/agent/src/entrypoint.rs:821]:
```suggestion
    if !SafeIpTables::list_mirrord_rules(&ipt).await?.is_empty() {
        let tables = SafeIpTables::load(ipt, false).await?;
        Ok(tables.cleanup().await?)
    } else {
        trace!("No mirorrd rules found, skipping iptables cleanup.");
        Ok(())
    }
```

nit: I would do something like this (personal preference for returning expressions), but it's up to you (don't think we ever discussed anything about this particular style thing).

File: mirrord/agent/iptables/src/lib.rs [hunk 2]
```diff
@@ -219,8 +219,7 @@ where
 
     /// List rules from other/ previous mirrord agents that exist on the IP table
     #[tracing::instrument(level = Level::TRACE, skip(ipt) ret, err)]
-    pub async fn list_mirrord_rules(ipt: IPT) -> IPTablesResult<Vec<String>> {
-        let ipt = Arc::new(ipt);
```
Comment (meowjesty) [inline mirrord/agent/iptables/src/lib.rs:223]: Why did we have this?

**Review by meowjesty — APPROVED** [review]
:+1:

File: mirrord/agent/iptables/src/lib.rs (hunk 2 above)
Comment (0x00A5) [reply mirrord/agent/iptables/src/lib.rs:223]: Not sure, maybe some cleanup that's overlooked.

File: mirrord/agent/src/entrypoint.rs (hunk 1 above)
Comment (0x00A5) [reply mirrord/agent/src/entrypoint.rs]: Updated, thanks!
